# Census Data Pipeline -- Geographic Hierarchy

Reorganized data pipeline fetching Census ACS + economic data at every level of the Census geographic hierarchy. Each section is self-contained with its own data fetch, save, and visualization.

**Geographic hierarchy** (coarse → fine):
1. **National** -- FRED macro indicators (CPI, interest rates, unemployment, housing starts)
2. **State** -- ACS 5-year demographics + FRED state unemployment
3. **County** -- ACS 5-year demographics + BLS LAUS county unemployment
4. **Tract** -- ACS 5-year demographics + TIGER/Line spatial join + FHFA HPI + OpenCelliD towers
5. **ZCTA (ZIP)** -- ACS 5-year demographics + Gazetteer centroids + FHFA HPI ZIP
6. **Block Group** -- ACS 5-year demographics (latest year only, finest ACS geography)
7. **Block** -- Decennial Census population (2000/2010/2020)
8. **Temporal Trends** -- 1yr/3yr/5yr growth rates computed from the tract panel
9. **Hierarchical Imputation** -- Fill Census-suppressed values using geographic hierarchy
10. **Summary** -- Pipeline inventory, data quality report

**Year range**: 2015-2024 (10 ACS 5-year vintages), consistent across all levels.
**Features**: 35 raw Census variables + 13 derived FMV features at each level.
**Caching**: Every section checks for cached output files before making API calls.

---
## Setup, Imports & Shared Functions

In [19]:
import os, json, time, warnings
import requests
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

warnings.filterwarnings("ignore", category=FutureWarning)

_cwd = os.getcwd()
_project_root = _cwd if os.path.isdir(os.path.join(_cwd, "data")) or os.path.isfile(os.path.join(_cwd, ".env")) else os.path.dirname(_cwd)
_env_path = os.path.join(_project_root, ".env")

try:
    from dotenv import load_dotenv
    load_dotenv(_env_path)
    print(f".env loaded from: {_env_path}")
except ImportError:
    print("python-dotenv not installed; using environment variables")

CENSUS_API_KEY = os.environ.get("CENSUS_API_KEY", "")
FRED_API_KEY = os.environ.get("FRED_API_KEY", "")
BLS_API_KEY = os.environ.get("BLS_API_KEY", "")
OPENCELLID_API_KEY = os.environ.get("OPENCELLID_API_KEY", "")

print(f"Census API key:    {'SET (' + CENSUS_API_KEY[:8] + '...)' if CENSUS_API_KEY else 'NOT SET'}")
print(f"FRED API key:      {'SET' if FRED_API_KEY else 'NOT SET'}")
print(f"BLS API key:       {'SET' if BLS_API_KEY else 'NOT SET (optional)'}")
print(f"OpenCelliD API key: {'SET' if OPENCELLID_API_KEY else 'NOT SET'}")

DATA_DIR = os.path.join(_project_root, "data")
PROCESSED_DIR = os.path.join(DATA_DIR, "processed")
RAW_DIR = os.path.join(DATA_DIR, "raw")
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(PROCESSED_DIR, exist_ok=True)
os.makedirs(RAW_DIR, exist_ok=True)

.env loaded from: c:\Users\hp\Desktop\Personal_Projects\pj_feb\.env
Census API key:    SET (e2989642...)
FRED API key:      SET
BLS API key:       SET
OpenCelliD API key: SET

In [20]:
# ---- Timeline: 2015-2024 (10 ACS 5-year vintages) ----
# Defined ONCE here, used by ALL geographic levels for consistency.
YEARS = list(range(2015, 2025))
DATASET = "acs5"
print(f"Timeline: {YEARS[0]}-{YEARS[-1]} ({len(YEARS)} vintages)")

# State FIPS codes (01-56 + 72=PR, excluding unused 03,07,14,43,52)
SKIP_FIPS = {"03", "07", "14", "43", "52"}
ALL_STATE_FIPS = [f"{i:02d}" for i in range(1, 57) if f"{i:02d}" not in SKIP_FIPS]
ALL_STATE_FIPS.append("72")
print(f"State FIPS: {len(ALL_STATE_FIPS)} states/territories")

CENSUS_SENTINEL_VALUES = [
    -666666666, -333333333, -222222222, -999999999,
    -666666, -333333, -222222, -999999, -6666, -3333, -2222, -9999,
]

RENAME_MAP = {
    # Demographics
    "B01003_001E": "population", "B01002_001E": "median_age",
    "B19013_001E": "median_income", "B19301_001E": "per_capita_income",
    "B17001_002E": "poverty_population",
    # Housing value & rent
    "B25077_001E": "median_home_value", "B25064_001E": "median_rent",
    "B25071_001E": "rent_burden_pct", "B25105_001E": "median_monthly_housing_cost",
    "B25119_003E": "renter_median_income",
    # Housing stock
    "B25002_001E": "total_housing_units", "B25002_003E": "vacant_housing_units",
    "B25003_002E": "owner_occupied_units", "B25003_003E": "renter_occupied_units",
    "B25035_001E": "median_year_built",
    # Structure type (property-type differentiation)
    "B25024_002E": "units_1_detached",
    "B25024_008E": "units_20_to_49",
    "B25024_009E": "units_50_plus",
    # Vacancy breakdown
    "B25004_002E": "vacant_for_rent",
    "B25004_004E": "vacant_for_sale",
    "B25004_006E": "vacant_seasonal",
    # New construction
    "B25034_002E": "built_2014_or_later",
    # Commute (kept: total_commuters as economic activity proxy)
    "B08301_001E": "total_commuters",
    # Education
    "B15003_022E": "bachelors_degree", "B15003_023E": "masters_degree",
    # Employment
    "B23025_002E": "in_labor_force", "B23025_005E": "unemployed_civilian",
    "C24050_002E": "employed_agriculture_mining",
    "C24050_029E": "employed_professional_scientific",
    "B24011_001E": "median_earnings_ft",
    # Income distribution
    "B19001_002E": "hh_income_under_10k",
    "B19001_017E": "hh_income_200k_plus",
    # Telecom demand
    "B28002_004E": "broadband_any",
    "B28002_013E": "no_internet",
    # Migration / growth
    "B07001_017E": "moved_diff_county",
}

RAW_FEATURE_NAMES = list(RENAME_MAP.values())
DERIVED_FEATURE_NAMES = [
    "vacancy_rate", "owner_renter_ratio",
    "college_degree_pct", "labor_force_participation",
    "poverty_rate", "professional_employment_pct",
    "multifamily_pct", "single_family_pct",
    "rental_market_tightness", "new_construction_rate",
    "in_migration_rate", "broadband_penetration", "income_polarization",
]
print(f"Features: {len(RAW_FEATURE_NAMES)} raw + {len(DERIVED_FEATURE_NAMES)} derived")

FIPS_TO_ABBR = {
    "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA",
    "08": "CO", "09": "CT", "10": "DE", "11": "DC", "12": "FL",
    "13": "GA", "15": "HI", "16": "ID", "17": "IL", "18": "IN",
    "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME",
    "24": "MD", "25": "MA", "26": "MI", "27": "MN", "28": "MS",
    "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
    "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
    "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI",
    "45": "SC", "46": "SD", "47": "TN", "48": "TX", "49": "UT",
    "50": "VT", "51": "VA", "53": "WA", "54": "WV", "55": "WI",
    "56": "WY", "72": "PR",
}

Timeline: 2015-2024 (10 vintages)
State FIPS: 52 states/territories
Features: 35 raw + 13 derived

In [21]:
# ---- Shared functions used by every geographic level ----

def _fetch_batch(base_url, var_string, geo_params, api_key):
    """Fetch a single batch from Census API and return a DataFrame."""
    params = {"get": var_string, **geo_params}
    if api_key:
        params["key"] = api_key
    r = requests.get(base_url, params=params, timeout=60, verify=False)
    r.raise_for_status()
    data = r.json()
    return pd.DataFrame(data[1:], columns=data[0])


def fetch_census_three_batch(base_url, geo_params, api_key, rename_map, geo_keys,
                             include_c24050=True):
    """Fetch Census ACS data in three batches (API limit ~25 vars) and merge."""
    batch_a = (
        "B01003_001E,B01002_001E,B19013_001E,B19301_001E,B17001_002E,"
        "B25077_001E,B25064_001E,B25071_001E,B25105_001E,B25119_003E,"
        "B25002_001E,B25002_003E,B25003_002E,B25003_003E,B25035_001E,"
        "B08301_001E,NAME"
    )
    batch_b = (
        "B25024_002E,B25024_008E,B25024_009E,"
        "B25004_002E,B25004_004E,B25004_006E,B25034_002E,"
        "B15003_022E,B15003_023E,"
        "B23025_002E,B23025_005E,"
        "B24011_001E,NAME"
    )
    batch_c_vars = [
        "B19001_002E", "B19001_017E",
        "B28002_004E", "B28002_013E",
        "B07001_017E",
    ]
    if include_c24050:
        batch_c_vars += ["C24050_002E", "C24050_029E"]
    batch_c = ",".join(batch_c_vars) + ",NAME"

    df_a = _fetch_batch(base_url, batch_a, geo_params, api_key)
    time.sleep(0.2)
    df_b = _fetch_batch(base_url, batch_b, geo_params, api_key)
    time.sleep(0.2)

    # Batch C: try all at once first; if it fails (older vintages missing
    # B28002/B07001), fall back to fetching each variable individually
    try:
        df_c = _fetch_batch(base_url, batch_c, geo_params, api_key)
    except Exception:
        df_c = None
        for var_id in batch_c_vars:
            try:
                df_single = _fetch_batch(base_url, f"{var_id},NAME", geo_params, api_key)
                if df_c is None:
                    df_c = df_single
                else:
                    df_c = df_c.merge(
                        df_single.drop(columns=["NAME"], errors="ignore"),
                        on=geo_keys, how="left",
                    )
            except Exception:
                pass
            time.sleep(0.15)

    df_merged = df_a.merge(
        df_b.drop(columns=["NAME"], errors="ignore"), on=geo_keys, how="left"
    )
    if df_c is not None and len(df_c) > 0:
        df_merged = df_merged.merge(
            df_c.drop(columns=["NAME"], errors="ignore"), on=geo_keys, how="left"
        )

    # Fill any missing batch-C columns with NaN
    for c_var in batch_c_vars:
        if c_var not in df_merged.columns:
            df_merged[c_var] = np.nan
    if not include_c24050:
        for c in ("C24050_002E", "C24050_029E"):
            if c not in df_merged.columns:
                df_merged[c] = np.nan

    df_merged.rename(columns=rename_map, inplace=True)
    numeric_cols = [c for c in rename_map.values() if c in df_merged.columns]
    for col in numeric_cols:
        df_merged[col] = pd.to_numeric(df_merged[col], errors="coerce")
    if numeric_cols:
        df_merged[numeric_cols] = df_merged[numeric_cols].replace(CENSUS_SENTINEL_VALUES, np.nan)
    return df_merged


def compute_fmv_derived(df):
    """Compute 13 derived FMV features with denominator-safe NaN propagation."""
    out = df.copy()
    _nan = lambda col: pd.Series(np.nan, index=out.index)
    _zero = lambda col: pd.Series(0.0, index=out.index)
    _pos = lambda s: s.where(s > 0, np.nan)

    pop = _pos(out.get("population", _nan("population")))
    th  = _pos(out.get("total_housing_units", _nan("th")))
    ro  = _pos(out.get("renter_occupied_units", _nan("ro")))
    lf  = _pos(out.get("in_labor_force", _nan("lf")))

    out["vacancy_rate"] = out.get("vacant_housing_units", _nan("v")) / th
    out["owner_renter_ratio"] = out.get("owner_occupied_units", _nan("o")) / ro

    ed = (out.get("bachelors_degree", _zero("b")).fillna(0)
          + out.get("masters_degree", _zero("m")).fillna(0))
    out["college_degree_pct"] = ed / pop * 100.0
    out["labor_force_participation"] = lf / pop * 100.0
    out["poverty_rate"] = out.get("poverty_population", _nan("p")) / pop * 100.0
    out["professional_employment_pct"] = out.get("employed_professional_scientific", _nan("e")) / lf * 100.0

    u20 = out.get("units_20_to_49", _zero("u20")).fillna(0)
    u50 = out.get("units_50_plus", _zero("u50")).fillna(0)
    out["multifamily_pct"] = (u20 + u50) / th * 100.0
    out["single_family_pct"] = out.get("units_1_detached", _nan("sf")) / th * 100.0

    out["rental_market_tightness"] = 1.0 - (out.get("vacant_for_rent", _nan("vr")) / ro)
    out["new_construction_rate"] = out.get("built_2014_or_later", _nan("nc")) / th * 100.0
    out["in_migration_rate"] = out.get("moved_diff_county", _nan("mg")) / pop * 100.0
    out["broadband_penetration"] = out.get("broadband_any", _nan("bb")) / th * 100.0

    hi = out.get("hh_income_200k_plus", _zero("hi")).fillna(0)
    lo = out.get("hh_income_under_10k", _zero("lo")).fillna(0)
    out["income_polarization"] = hi / (lo + 1)

    return out


def fetch_acs_level(geo_params, geo_keys, extra_cols_fn=None, label=""):
    """Generic ACS fetch loop over YEARS with caching-friendly structure."""
    frames, errors = [], []
    for yr in YEARS:
        base_url = f"https://api.census.gov/data/{yr}/acs/{DATASET}"
        try:
            df_yr = fetch_census_three_batch(
                base_url, geo_params, CENSUS_API_KEY, RENAME_MAP, geo_keys,
                include_c24050=(yr >= 2012),
            )
            df_yr["year"] = yr
            if extra_cols_fn:
                df_yr = extra_cols_fn(df_yr)
            df_yr = compute_fmv_derived(df_yr)
            frames.append(df_yr)
            print(f"  {yr}: {len(df_yr):,} {label}  [OK]")
        except Exception as e:
            errors.append(f"{yr}: {e}")
            print(f"  {yr}: ERROR - {e}")
        time.sleep(0.3)
    df_all = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    return df_all, errors


print("Shared functions loaded: fetch_census_three_batch, compute_fmv_derived, fetch_acs_level")

Shared functions loaded: fetch_census_three_batch, compute_fmv_derived, fetch_acs_level

---
## 1. National Level -- FRED Macro Economic Indicators

Macro factors that apply uniformly to all geographies. Joined by `year` as a scalar.

| Group | Series | Description | Frequency |
|-------|--------|-------------|-----------|
| Inflation | CPIAUCSL | CPI (All Urban Consumers) | Monthly |
| Inflation | CSUSHPINSA | Case-Shiller US Home Price Index | Monthly |
| Inflation | MSPUS | Median Sales Price of Houses Sold | Quarterly |
| Interest Rates | DGS10 | 10-Year Treasury Rate | Daily |
| Interest Rates | FEDFUNDS | Federal Funds Effective Rate | Monthly |
| Interest Rates | MORTGAGE30US | 30-Year Fixed Rate Mortgage | Weekly |
| Employment | UNRATE | National Unemployment Rate | Monthly |
| Employment | PAYEMS | Nonfarm Payrolls (thousands) | Monthly |
| Economy | GDP | Gross Domestic Product | Quarterly |
| Housing Supply | HOUST | Housing Starts (thousands) | Monthly |
| Housing Supply | PERMIT | New Housing Permits | Monthly |
| Sentiment | UMCSENT | Consumer Sentiment (UMich) | Monthly |

In [22]:
# ---- Section 1: FRED National Macro Series (12 indicators) ----
fred_path = os.path.join(PROCESSED_DIR, "fred_national_macro.parquet")

FRED_SERIES_MAP = {
    # Inflation / Prices
    "CPIAUCSL":     "CPI (All Urban Consumers)",
    "CSUSHPINSA":   "Case-Shiller Home Price Index",
    "MSPUS":        "Median Sales Price of Houses Sold",
    # Interest Rates / Credit
    "DGS10":        "10-Year Treasury Rate",
    "FEDFUNDS":     "Federal Funds Effective Rate",
    "MORTGAGE30US": "30-Year Fixed Mortgage Rate",
    # Employment
    "UNRATE":       "National Unemployment Rate",
    "PAYEMS":       "Nonfarm Payrolls (thousands)",
    # Economy
    "GDP":          "Gross Domestic Product",
    # Housing Supply
    "HOUST":        "Housing Starts (thousands)",
    "PERMIT":       "New Housing Permits",
    # Sentiment
    "UMCSENT":      "Consumer Sentiment (UMich)",
}

# Auto-invalidate cache if new series were added
if os.path.isfile(fred_path):
    df_fred_national = pd.read_parquet(fred_path)
    missing_series = [s for s in FRED_SERIES_MAP if s not in df_fred_national.columns]
    if missing_series:
        print(f"Cache missing {len(missing_series)} series: {missing_series} -- re-fetching")
        os.remove(fred_path)
    else:
        print(f"Loading cached: {fred_path}")
        print(f"  {len(df_fred_national):,} rows | cols: {list(df_fred_national.columns)}")

if not os.path.isfile(fred_path):
    from fredapi import Fred
    fred_client = Fred(api_key=FRED_API_KEY)
    fred_frames = []
    print(f"Fetching {len(FRED_SERIES_MAP)} FRED series (start: 2005-01-01)...")
    for sid, label in FRED_SERIES_MAP.items():
        try:
            s = fred_client.get_series(sid, observation_start="2005-01-01")
            df_s = s.dropna().reset_index()
            df_s.columns = ["date", sid]
            fred_frames.append(df_s)
            latest_val  = s.dropna().iloc[-1]
            latest_date = s.dropna().index[-1].strftime("%Y-%m-%d")
            n_obs = len(s.dropna())
            print(f"  [OK]  {label:40s} | {latest_val:>12.2f} ({latest_date}) | {n_obs:,} obs")
        except Exception as e:
            print(f"  [ERR] {label:40s} | {e}")
        time.sleep(0.2)

    if fred_frames:
        df_fred_national = fred_frames[0]
        for df_f in fred_frames[1:]:
            df_fred_national = df_fred_national.merge(df_f, on="date", how="outer")
        df_fred_national = df_fred_national.sort_values("date").reset_index(drop=True)
        df_fred_national.to_parquet(fred_path, index=False)
        print(f"Saved: {fred_path} ({len(df_fred_national):,} rows x {len(df_fred_national.columns)} cols)")
    else:
        df_fred_national = pd.DataFrame()
        print("No FRED data retrieved")

Fetching 12 FRED series (start: 2005-01-01)...
  [OK]  CPI (All Urban Consumers)                |       326.59 (2026-01-01) | 252 obs
  [OK]  Case-Shiller Home Price Index            |       327.45 (2025-12-01) | 252 obs
  [OK]  Median Sales Price of Houses Sold        |    405300.00 (2025-10-01) | 84 obs
  [OK]  10-Year Treasury Rate                    |         4.02 (2026-02-26) | 5,291 obs
  [OK]  Federal Funds Effective Rate             |         3.64 (2026-01-01) | 253 obs
  [OK]  30-Year Fixed Mortgage Rate              |         5.98 (2026-02-26) | 1,104 obs
  [OK]  National Unemployment Rate               |         4.30 (2026-01-01) | 252 obs
  [OK]  Nonfarm Payrolls (thousands)             |    158627.00 (2026-01-01) | 253 obs
  [OK]  Gross Domestic Product                   |     31490.07 (2025-10-01) | 84 obs
  [OK]  Housing Starts (thousands)               |      1404.00 (2025-12-01) | 252 obs
  [OK]  New Housing Permits                      |      1448.00 (2025-12-01) | 252 obs
  [OK]  Consumer Sentiment (UMich)               |        56.40 (2026-01-01) | 253 obs
Saved: c:\Users\hp\Desktop\Personal_Projects\pj_feb\data\processed\fred_national_macro.parquet (5,382 rows x 13 cols)

In [23]:
# ---- Viz: FRED National Macro Indicators -- Timeline (2005-present) ----
if len(df_fred_national) > 0:
    avail = [s for s in FRED_SERIES_MAP if s in df_fred_national.columns]
    n_cols = 3
    n_rows = (len(avail) + n_cols - 1) // n_cols
    fig_fred = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=[FRED_SERIES_MAP[s] for s in avail],
        vertical_spacing=0.09, horizontal_spacing=0.07,
    )
    palette = [
        "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728",
        "#9467bd", "#8c564b", "#e377c2", "#7f7f7f",
        "#bcbd22", "#17becf", "#aec7e8", "#ffbb78",
    ]
    for idx, sid in enumerate(avail):
        r = idx // n_cols + 1
        c = idx % n_cols + 1
        vals = df_fred_national[["date", sid]].dropna()
        fig_fred.add_trace(
            go.Scatter(
                x=vals["date"], y=vals[sid],
                name=FRED_SERIES_MAP[sid],
                line=dict(color=palette[idx % len(palette)], width=1.8),
                showlegend=False,
            ),
            row=r, col=c,
        )
    fig_fred.update_layout(
        title="National Level -- FRED Macro Economic Indicators (2005-present)",
        height=280 * n_rows, margin=dict(l=50, r=30, t=80, b=40),
    )
    fig_fred.show()
else:
    print("No FRED data to plot")

In [24]:
# ---- FRED Macro Trend Slopes (5yr / 10yr) ----
# The FRED window (2005-present) is intentionally wider than the ACS window
# (2015-2024).  We exploit this longer history to compute rolling trend slopes
# that capture macro momentum for each ACS vintage year.

from scipy.stats import linregress

def compute_fred_trend_slopes(df_fred, series_cols, years, windows=(5, 10)):
    """Compute linear-regression slopes over trailing windows for each year.
    Returns a DataFrame indexed by year with {series}_slope_{w}yr columns."""
    df = df_fred.copy()
    df["date"] = pd.to_datetime(df["date"])
    df["year"] = df["date"].dt.year
    df["month_idx"] = (df["date"].dt.year - df["date"].dt.year.min()) * 12 + df["date"].dt.month

    rows = []
    for yr in years:
        row = {"year": yr}
        for w in windows:
            start = pd.Timestamp(f"{yr - w}-01-01")
            end = pd.Timestamp(f"{yr}-12-31")
            mask = (df["date"] >= start) & (df["date"] <= end)
            sub = df.loc[mask].dropna(subset=["month_idx"])
            for col in series_cols:
                key = f"{col}_slope_{w}yr"
                vals = sub.dropna(subset=[col])
                if len(vals) >= 12:
                    slope, _, _, _, _ = linregress(vals["month_idx"], vals[col])
                    row[key] = slope
                else:
                    row[key] = np.nan
        rows.append(row)

    return pd.DataFrame(rows)

fred_trend_path = os.path.join(PROCESSED_DIR, "fred_national_trend_slopes.parquet")

if os.path.isfile(fred_trend_path):
    print(f"Loading cached: {fred_trend_path}")
    df_fred_trends = pd.read_parquet(fred_trend_path)
else:
    fred_series_cols = [c for c in FRED_SERIES_MAP.keys() if c in df_fred_national.columns]
    df_fred_trends = compute_fred_trend_slopes(df_fred_national, fred_series_cols, YEARS)
    df_fred_trends.to_parquet(fred_trend_path, index=False)
    print(f"Saved: {fred_trend_path}")

print(f"FRED trend slopes: {len(df_fred_trends)} years x {len(df_fred_trends.columns)-1} features")
print(f"  Columns: {[c for c in df_fred_trends.columns if c != 'year'][:6]}...")
df_fred_trends.head(3)

Saved: c:\Users\hp\Desktop\Personal_Projects\pj_feb\data\processed\fred_national_trend_slopes.parquet
FRED trend slopes: 10 years x 24 features
  Columns: ['CPIAUCSL_slope_5yr', 'CSUSHPINSA_slope_5yr', 'MSPUS_slope_5yr', 'DGS10_slope_5yr', 'FEDFUNDS_slope_5yr', 'MORTGAGE30US_slope_5yr']...

,year,CPIAUCSL_slope_5yr,CSUSHPINSA_slope_5yr,MSPUS_slope_5yr,DGS10_slope_5yr,FEDFUNDS_slope_5yr,MORTGAGE30US_slope_5yr,UNRATE_slope_5yr,PAYEMS_slope_5yr,GDP_slope_5yr,...,MSPUS_slope_10yr,DGS10_slope_10yr,FEDFUNDS_slope_10yr,MORTGAGE30US_slope_10yr,UNRATE_slope_10yr,PAYEMS_slope_10yr,GDP_slope_10yr,HOUST_slope_10yr,PERMIT_slope_10yr,UMCSENT_slope_10yr
0,2015,0.317018,0.543720,1330.000000,-0.013927,-0.000636,-0.011517,-0.072881,191.562367,54.516330,...,423.232323,-0.023337,-0.040104,-0.023716,0.014690,29.559892,40.022984,-7.189123,-7.114626,0.010124
1,2016,0.244087,0.745297,1352.304348,-0.008646,0.003345,-0.007667,-0.070871,208.331082,54.514107,...,600.763448,-0.023753,-0.036296,-0.024501,-0.000263,56.114353,41.523151,-2.205011,-1.972367,0.106590
2,2017,0.238003,0.812582,1239.710145,0.001840,0.012416,0.000879,-0.063982,211.749260,55.520187,...,826.572704,-0.018213,-0.020104,-0.019914,-0.019168,94.373701,45.250707,2.418071,2.812956,0.212273

---
## 2. State Level -- ACS Demographics + FRED State Macro Indicators

**Source**: Census ACS 5-year (35+13 vars) + FRED state-level economic indicators (same structure as National).

| Series pattern | Description | Frequency |
|----------------|-------------|-----------|
| {ST}UR | Unemployment rate | Monthly |
| {ST}RGSP | Real GDP (millions chained 2017$) | Annual |
| {ST}BPPRIV | New private housing units authorized (building permits) | Monthly |

**Fetch**: ACS — 1 call per year. FRED — one series per state per indicator (cached).
**Join key**: `state` FIPS, `state_abbr`, `year`

In [26]:
# ---- Section 2: State-Level ACS (2015-2024) ----
state_path = os.path.join(DATA_DIR, "census_state_demographics_2015_2024.csv")

if os.path.isfile(state_path):
    df_states_all = pd.read_csv(state_path)
    cached_years = set(df_states_all["year"].unique())
    expected_years = set(YEARS)
    missing = expected_years - cached_years
    if missing:
        print(f"Cache missing years {sorted(missing)} -- re-fetching all {len(YEARS)} years")
        os.remove(state_path)
    else:
        print(f"Loading cached: {state_path}")

if not os.path.isfile(state_path):
    print(f"Fetching state-level: {len(YEARS)} years, 35 raw + 13 derived features")
    df_states_all, state_errors = fetch_acs_level(
        {"for": "state:*"}, ["state"], label="states"
    )
    df_states_all.to_csv(state_path, index=False)
    print(f"Saved: {state_path}")
    if state_errors:
        print(f"Errors: {state_errors}")
    df_states_all = pd.read_csv(state_path)

latest_year = int(df_states_all["year"].max())
df_states = df_states_all[df_states_all["year"] == latest_year].copy()

print(f"\n--- State-Level: {len(df_states_all):,} rows x {len(df_states_all.columns)} cols ---")
print(f"Years: {int(df_states_all['year'].min())}-{latest_year} | States/yr: {len(df_states)}")
df_states_all.head(5)

Fetching state-level: 10 years, 35 raw + 13 derived features

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2015: ERROR - 400 Client Error:  for url: https://api.census.gov/data/2015/acs/acs5?get=B19001_002E%2CB19001_017E%2CB28002_004E%2CB28002_013E%2CB07001_017E%2CC24050_002E%2CC24050_029E%2CNAME&for=state%3A%2A&key=e29896428e8aef86a3bd033944a85539a7babede

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2016: ERROR - 400 Client Error:  for url: https://api.census.gov/data/2016/acs/acs5?get=B19001_002E%2CB19001_017E%2CB28002_004E%2CB28002_013E%2CB07001_017E%2CC24050_002E%2CC24050_029E%2CNAME&for=state%3A%2A&key=e29896428e8aef86a3bd033944a85539a7babede

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2017: 52 states  [OK]

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2018: 52 states  [OK]

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2019: 52 states  [OK]

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2020: 52 states  [OK]

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2021: 52 states  [OK]

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2022: 52 states  [OK]

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2023: 52 states  [OK]

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2024: 52 states  [OK]
Saved: c:\Users\hp\Desktop\Personal_Projects\pj_feb\data\census_state_demographics_2015_2024.csv
Errors: ['2015: 400 Client Error:  for url: https://api.census.gov/data/2015/acs/acs5?get=B19001_002E%2CB19001_017E%2CB28002_004E%2CB28002_013E%2CB07001_017E%2CC24050_002E%2CC24050_029E%2CNAME&for=state%3A%2A&key=e29896428e8aef86a3bd033944a85539a7babede', '2016: 400 Client Error:  for url: https://api.census.gov/data/2016/acs/acs5?get=B19001_002E%2CB19001_017E%2CB28002_004E%2CB28002_013E%2CB07001_017E%2CC24050_002E%2CC24050_029E%2CNAME&for=state%3A%2A&key=e29896428e8aef86a3bd033944a85539a7babede']

--- State-Level: 416 rows x 51 cols ---
Years: 2017-2024 | States/yr: 52

,population,median_age,median_income,per_capita_income,poverty_population,median_home_value,median_rent,rent_burden_pct,median_monthly_housing_cost,renter_median_income,...,labor_force_participation,poverty_rate,professional_employment_pct,multifamily_pct,single_family_pct,rental_market_tightness,new_construction_rate,in_migration_rate,broadband_penetration,income_polarization
0,2986220,36.9,42009,22500,620007,109300,740,30.1,692,26144,...,45.203100,20.762268,16.185038,2.165091,69.164668,0.896040,0.940104,85.299476,54.201806,0.227919
1,6075300,38.4,51542,28282,861679,145400,784,28.4,834,31469,...,50.411618,14.183316,16.504884,4.575337,70.346693,0.926622,0.680322,83.333449,64.806586,0.555381
2,1029862,39.8,50801,28706,144198,209100,751,28.1,799,31618,...,51.112479,14.001682,17.933350,3.450416,69.355556,0.936719,1.053285,82.961892,63.771430,0.543950
3,1893921,36.3,56675,29866,220330,142400,773,26.6,866,34629,...,54.437593,11.633537,15.690904,6.666659,72.670036,0.941487,0.943973,82.687345,71.266938,0.729166
4,2887725,37.7,55434,28450,405263,216400,1017,29.5,1065,40528,...,50.743059,14.033989,24.728319,8.796957,59.766786,0.906721,1.102979,79.701391,68.405683,0.663325

In [27]:
# ---- FRED State-Level Macro Indicators (same approach as National) ----
# Series pattern {ST} = state abbreviation (e.g. CA, TX). Full time series per state.
state_macro_path = os.path.join(PROCESSED_DIR, "fred_state_macro.parquet")

FRED_STATE_SERIES_MAP = {
    "{ST}UR":       ("unemployment_rate",   "Unemployment Rate"),
    "{ST}RGSP":     ("real_gdp",             "Real GDP (mil chained 2017$)"),
    "{ST}BPPRIV":   ("building_permits",     "Building Permits (private)"),
}

# States to fetch (exclude PR/DC for some series that may not exist)
STATE_ABBR_FOR_FRED = [abbr for abbr in sorted(FIPS_TO_ABBR.values()) if abbr not in ("PR", "DC")]

if os.path.isfile(state_macro_path):
    print(f"Loading cached: {state_macro_path}")
    df_state_macro = pd.read_parquet(state_macro_path)
    missing = [k for k in FRED_STATE_SERIES_MAP if FRED_STATE_SERIES_MAP[k][0] not in df_state_macro.columns]
    if missing:
        print(f"  Cache missing series {missing} -- re-fetching")
        os.remove(state_macro_path)

if not os.path.isfile(state_macro_path):
    from fredapi import Fred
    fred_client = Fred(api_key=FRED_API_KEY)
    print(f"Fetching FRED state-level indicators for {len(STATE_ABBR_FOR_FRED)} states (start: 2005-01-01)...")
    print("  Series: Unemployment Rate, Real GDP, Building Permits")
    long_rows = []
    for abbr in STATE_ABBR_FOR_FRED:
        for pattern, (col_name, label) in FRED_STATE_SERIES_MAP.items():
            sid = pattern.replace("{ST}", abbr)
            try:
                s = fred_client.get_series(sid, observation_start="2005-01-01")
                s = s.dropna()
                if len(s) == 0:
                    continue
                for dt, val in s.items():
                    long_rows.append({"state_abbr": abbr, "date": dt, "variable": col_name, "value": float(val)})
            except Exception:
                pass
            time.sleep(0.15)
        if (STATE_ABBR_FOR_FRED.index(abbr) + 1) % 10 == 0:
            print(f"  Progress: {STATE_ABBR_FOR_FRED.index(abbr)+1}/{len(STATE_ABBR_FOR_FRED)} states")

    if long_rows:
        df_long = pd.DataFrame(long_rows)
        df_long["date"] = pd.to_datetime(df_long["date"])
        df_state_macro = df_long.pivot_table(
            index=["state_abbr", "date"], columns="variable", values="value", aggfunc="first"
        ).reset_index()
        df_state_macro.to_parquet(state_macro_path, index=False)
        print(f"Saved: {state_macro_path} ({len(df_state_macro):,} rows x {len(df_state_macro.columns)} cols)")
    else:
        df_state_macro = pd.DataFrame()
        print("No FRED state data retrieved")

# Backward compatibility: df_state_ur = latest unemployment rate per state (for downstream BLS merge / summary)
if len(df_state_macro) > 0 and "unemployment_rate" in df_state_macro.columns:
    df_state_ur = (
        df_state_macro.dropna(subset=["unemployment_rate"])
        .sort_values("date")
        .groupby("state_abbr")["unemployment_rate"]
        .last()
        .reset_index()
    )
else:
    df_state_ur = pd.DataFrame(columns=["state_abbr", "unemployment_rate"])

print(f"State macro: {len(df_state_macro):,} rows | State unemployment (latest): {len(df_state_ur)} states")
df_state_ur.sort_values("unemployment_rate", ascending=False).head(10)

Fetching FRED state-level indicators for 50 states (start: 2005-01-01)...
  Series: Unemployment Rate, Real GDP, Building Permits
  Progress: 10/50 states
  Progress: 20/50 states
  Progress: 30/50 states
  Progress: 40/50 states
  Progress: 50/50 states
Saved: c:\Users\hp\Desktop\Personal_Projects\pj_feb\data\processed\fred_state_macro.parquet (12,600 rows x 5 cols)
State macro: 12,600 rows | State unemployment (latest): 50 states

   state_abbr  unemployment_rate
4          CA                5.5
30         NJ                5.4
32         NV                5.2
36         OR                5.2
7          DE                5.2
21         MI                5.0
0          AK                4.8
39         SC                4.8
18         MA                4.8
46         WA                4.7

In [8]:
# ---- Viz: State-Level FRED Indicators -- Timeline (2005-present), 3 panels like National ----
if len(df_state_macro) > 0:
    state_vars = [
        ("unemployment_rate", "Median State Unemployment Rate (%)", "#1f77b4"),
        ("real_gdp", "Median State Real GDP (mil chained 2017$)", "#2ca02c"),
        ("building_permits", "Total State Building Permits", "#ff7f0e"),
    ]
    avail = [(col, title, color) for col, title, color in state_vars if col in df_state_macro.columns]
    if avail:
        fig = make_subplots(rows=3, cols=1, subplot_titles=[t for _, t, _ in avail],
                            vertical_spacing=0.10, shared_xaxes=True)
        for idx, (col, title, color) in enumerate(avail):
            if col == "building_permits":
                agg = df_state_macro.groupby("date")[col].sum().reset_index()
            else:
                agg = df_state_macro.groupby("date")[col].median().reset_index()
            fig.add_trace(
                go.Scatter(x=agg["date"], y=agg[col], name=title, line=dict(color=color, width=2), showlegend=False),
                row=idx + 1, col=1,
            )
        fig.update_layout(title="State Level -- FRED Economic Indicators (2005-present)", height=520, margin=dict(t=80))
        fig.update_xaxes(dtick="M12")
        fig.show()
    else:
        print("No state FRED series to plot")
else:
    print("No state macro data for FRED timeline")

In [28]:
# ---- Viz: State-Level Animated Choropleth (Median Income) ----
df_states_all["state_abbr"] = df_states_all["state"].astype(str).str.zfill(2).map(FIPS_TO_ABBR)
df_map_all = df_states_all.dropna(subset=["state_abbr", "median_income"]).copy()
df_map_all = df_map_all[df_map_all["median_income"] > 0]

fig_income = px.choropleth(
    df_map_all.sort_values("year"), locations="state_abbr", locationmode="USA-states",
    color="median_income", scope="usa", animation_frame="year",
    color_continuous_scale="Viridis",
    range_color=[30000, df_map_all["median_income"].quantile(0.98)],
    hover_name="NAME", hover_data={"median_income": ":$,.0f", "population": ":,.0f",
                                    "median_home_value": ":$,.0f", "state_abbr": False, "year": True},
    labels={"median_income": "Median Income ($)", "year": "Year"},
    title="Census ACS -- Median Household Income by State (2015-2024)",
)
fig_income.update_layout(geo=dict(bgcolor="rgba(0,0,0,0)"), margin=dict(l=0, r=0, t=50, b=0), height=500)
fig_income.show()

In [29]:
# ---- Viz: State-Level Timeline (2015-2024) -- National Median of Key ACS Attributes ----
if len(df_states_all) > 0:
    key_attrs = ["median_income", "median_home_value", "median_rent",
                 "poverty_rate", "vacancy_rate", "college_degree_pct"]
    avail = [a for a in key_attrs if a in df_states_all.columns]
    df_st_ann = df_states_all.groupby("year")[avail].median().reset_index()
    n_cols = 3
    n_rows = (len(avail) + n_cols - 1) // n_cols
    fig = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=[a.replace("_", " ").title() for a in avail],
        shared_xaxes=True, vertical_spacing=0.12,
    )
    colors = px.colors.qualitative.Plotly
    for idx, attr in enumerate(avail):
        r, c = divmod(idx, n_cols)
        fig.add_trace(
            go.Scatter(x=df_st_ann["year"], y=df_st_ann[attr],
                       mode="lines+markers", name=attr.replace("_", " ").title(),
                       line=dict(color=colors[idx % len(colors)], width=2.5),
                       showlegend=False),
            row=r + 1, col=c + 1,
        )
    fig.update_layout(
        title="State Level -- National Median Trends (2015-2024)",
        height=420 * n_rows, margin=dict(l=50, r=30, t=80, b=40),
    )
    fig.update_xaxes(dtick=2)
    fig.show()
else:
    print("No state data for timeline visualization")

---
## 3. County Level -- ACS Demographics + BLS LAUS Unemployment

**Source**: Census ACS 5-year (35+13 vars) + BLS LAUS (county-level monthly unemployment)
**Fetch**: ACS -- 1 call per year. BLS -- chunked POST (50 series/chunk)
**Join key**: `county_fips = state + county`, `year`

In [30]:
# ---- Section 3a: County-Level ACS (2015-2024) ----
county_path = os.path.join(DATA_DIR, "census_county_demographics_2015_2024.csv")

if os.path.isfile(county_path):
    print(f"Loading cached: {county_path}")
    df_counties_all = pd.read_csv(county_path, dtype={"state": str, "county": str})
else:
    def _add_county_fips(df):
        df["county_fips"] = df["state"].astype(str).str.zfill(2) + df["county"].astype(str).str.zfill(3)
        return df

    print(f"Fetching county-level: {len(YEARS)} years, 35 vars (three-batch)")
    df_counties_all, county_errors = fetch_acs_level(
        {"for": "county:*"}, ["state", "county"],
        extra_cols_fn=_add_county_fips, label="counties"
    )
    df_counties_all.to_csv(county_path, index=False)
    print(f"Saved: {county_path}")
    if county_errors:
        print(f"Errors: {county_errors}")

df_counties_all["state"] = df_counties_all["state"].astype(str).str.zfill(2)
df_counties_all["county"] = df_counties_all["county"].astype(str).str.zfill(3)
df_counties_all["county_fips"] = df_counties_all["state"] + df_counties_all["county"]

df_counties = df_counties_all[df_counties_all["year"] == latest_year].copy()
print(f"\n--- County-Level: {len(df_counties_all):,} rows x {len(df_counties_all.columns)} cols ---")
print(f"Years: {int(df_counties_all['year'].min())}-{int(df_counties_all['year'].max())} | Counties/yr: {len(df_counties):,}")

Fetching county-level: 10 years, 35 vars (three-batch)

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2015: ERROR - 400 Client Error:  for url: https://api.census.gov/data/2015/acs/acs5?get=B19001_002E%2CB19001_017E%2CB28002_004E%2CB28002_013E%2CB07001_017E%2CC24050_002E%2CC24050_029E%2CNAME&for=county%3A%2A&key=e29896428e8aef86a3bd033944a85539a7babede

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2016: ERROR - 400 Client Error:  for url: https://api.census.gov/data/2016/acs/acs5?get=B19001_002E%2CB19001_017E%2CB28002_004E%2CB28002_013E%2CB07001_017E%2CC24050_002E%2CC24050_029E%2CNAME&for=county%3A%2A&key=e29896428e8aef86a3bd033944a85539a7babede

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

  2017: 3,220 counties  [OK]

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning:

Unverified HTTPS request is being made to host 'api.census.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

KeyboardInterrupt:

In [ ]:
# ---- Section 3b: BLS LAUS County Unemployment ----
bls_county_path = os.path.join(PROCESSED_DIR, "bls_laus_county.parquet")

if os.path.isfile(bls_county_path):
    print(f"Loading cached: {bls_county_path}")
    df_bls_county = pd.read_parquet(bls_county_path)
else:
    county_fips_list = df_counties_all["county_fips"].dropna().unique().tolist()
    county_series = [f"LAUCN{fips}0000000003" for fips in county_fips_list]

    bls_url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
    bls_base = {"startyear": "2020", "endyear": "2025"}
    if BLS_API_KEY:
        bls_base["registrationkey"] = BLS_API_KEY

    county_ur_records = []
    chunk_size = 50
    print(f"Fetching BLS LAUS: {len(county_series)} series in {len(county_series)//chunk_size + 1} chunks")
    for i in range(0, len(county_series), chunk_size):
        chunk = county_series[i: i + chunk_size]
        payload = {**bls_base, "seriesid": chunk}
        try:
            r_bls = requests.post(bls_url, json=payload, timeout=60)
            j = r_bls.json()
            if j.get("status") != "REQUEST_SUCCEEDED":
                msg = j.get("message", "")
                if "threshold" in str(msg).lower():
                    print(f"  Rate limit at chunk {i//chunk_size}, stopping.")
                    break
                continue
            for s in j.get("Results", {}).get("series", []):
                sid = s.get("seriesID", "")
                cfips = sid[5:10] if len(sid) >= 10 else ""
                for d in s.get("data", []):
                    county_ur_records.append({
                        "county_fips": cfips, "year": d.get("year"),
                        "period": d.get("period"),
                        "unemployment_rate": pd.to_numeric(d.get("value"), errors="coerce"),
                    })
        except Exception as e:
            print(f"  BLS chunk {i//chunk_size}: {e}")
        if (i // chunk_size) % 10 == 9:
            time.sleep(1)

    df_bls_county = pd.DataFrame(county_ur_records)
    df_bls_county = df_bls_county[
        df_bls_county["period"].astype(str).str.match(r"^M(0[1-9]|1[0-2])$")
    ].copy()
    df_bls_county.to_parquet(bls_county_path, index=False)
    print(f"Saved: {bls_county_path}")

df_bls_cty_latest = (
    df_bls_county.assign(
        year_int=pd.to_numeric(df_bls_county["year"], errors="coerce"),
        month_int=pd.to_numeric(df_bls_county["period"].str[1:], errors="coerce")
    ).sort_values(["year_int", "month_int"], ascending=[False, False])
    .drop_duplicates("county_fips", keep="first")
) if len(df_bls_county) > 0 else pd.DataFrame()

print(f"\n--- BLS County Unemployment ---")
print(f"  Records: {len(df_bls_county):,} | Counties: {df_bls_county['county_fips'].nunique() if len(df_bls_county) > 0 else 0}")

In [ ]:
# ---- Viz: County-Level Income Choropleth ----
from urllib.request import urlopen
import json as _json
with urlopen("https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json") as r:
    counties_geojson = _json.load(r)

df_county_map = df_counties_all[
    (df_counties_all["median_income"] > 0) & (df_counties_all["county_fips"].notna())
].copy()

fig_county = px.choropleth(
    df_county_map.sort_values("year"), geojson=counties_geojson, locations="county_fips",
    color="median_income", scope="usa", animation_frame="year",
    color_continuous_scale="Viridis",
    range_color=[25000, df_county_map["median_income"].quantile(0.98)],
    hover_data={"median_income": ":$,.0f", "population": ":,.0f", "county_fips": True, "year": True},
    labels={"median_income": "Median Income ($)", "county_fips": "FIPS", "year": "Year"},
    title="Census ACS -- Median Household Income by County (2015-2024)",
)
fig_county.update_layout(geo=dict(bgcolor="rgba(0,0,0,0)"), margin=dict(l=0, r=0, t=50, b=0), height=550)
fig_county.show()

In [ ]:
# ---- Viz: County-Level Timeline (2015-2024) -- National Median of Key ACS Attributes ----
if len(df_counties_all) > 0:
    key_attrs = ["median_income", "median_home_value", "median_rent",
                 "poverty_rate", "vacancy_rate", "labor_force_participation"]
    avail = [a for a in key_attrs if a in df_counties_all.columns]
    df_co_ann = df_counties_all.groupby("year")[avail].median().reset_index()
    n_cols = 3
    n_rows = (len(avail) + n_cols - 1) // n_cols
    fig = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=[a.replace("_", " ").title() for a in avail],
        shared_xaxes=True, vertical_spacing=0.12,
    )
    colors = px.colors.qualitative.Set2
    for idx, attr in enumerate(avail):
        r, c = divmod(idx, n_cols)
        fig.add_trace(
            go.Scatter(x=df_co_ann["year"], y=df_co_ann[attr],
                       mode="lines+markers", name=attr.replace("_", " ").title(),
                       line=dict(color=colors[idx % len(colors)], width=2.5),
                       showlegend=False),
            row=r + 1, col=c + 1,
        )
    fig.update_layout(
        title="County Level -- National Median Trends (2015-2024)",
        height=420 * n_rows, margin=dict(l=50, r=30, t=80, b=40),
    )
    fig.update_xaxes(dtick=2)
    fig.show()
else:
    print("No county data for timeline visualization")

---
## 4. Tract Level -- ACS + TIGER Spatial Join + FHFA HPI + OpenCelliD

**Source**: Census ACS 5-year (35+13 vars), TIGER/Line shapefiles, FHFA HPI (tract), OpenCelliD towers
**Fetch**: ACS -- 52 states x 10 years = 520 calls (caching critical). TIGER -- 52 ZIP downloads. OpenCelliD -- 1 bulk download.
**Join key**: `tract_fips = state + county + tract`, `year`

This is the highest-volume section. Caching is essential to avoid re-fetching.

In [ ]:
# ---- Section 4a: Tract-Level ACS (2015-2024) ----
tract_path = os.path.join(DATA_DIR, "census_tract_all_us_demographics_2015_2024.parquet")

if os.path.isfile(tract_path):
    print(f"Loading cached: {tract_path}")
    df_tracts_all = pd.read_parquet(tract_path)
else:
    all_tract_frames, tract_errors = [], []
    print(f"Fetching tract-level: {len(ALL_STATE_FIPS)} states x {len(YEARS)} years, 35 vars (three-batch)")
    for yr in YEARS:
        base_url = f"https://api.census.gov/data/{yr}/acs/{DATASET}"
        yr_frames = []
        for fips in ALL_STATE_FIPS:
            try:
                df_yr = fetch_census_three_batch(
                    base_url, {"for": "tract:*", "in": f"state:{fips}"},
                    CENSUS_API_KEY, RENAME_MAP, ["state", "county", "tract"],
                    include_c24050=(yr >= 2012),
                )
                df_yr["year"] = yr
                df_yr["tract_fips"] = df_yr["state"] + df_yr["county"] + df_yr["tract"]
                df_yr = compute_fmv_derived(df_yr)
                yr_frames.append(df_yr)
            except Exception as e:
                tract_errors.append(f"{yr}/{fips}: {e}")
            time.sleep(0.15)
        if yr_frames:
            df_yr_all = pd.concat(yr_frames, ignore_index=True)
            all_tract_frames.append(df_yr_all)
            print(f"  {yr}: {len(df_yr_all):,} tracts")

    df_tracts_all = pd.concat(all_tract_frames, ignore_index=True)
    try:
        df_tracts_all.to_parquet(tract_path, index=False, engine="pyarrow")
    except Exception:
        df_tracts_all.to_parquet(tract_path, index=False)
    print(f"Saved: {tract_path}")
    if tract_errors:
        print(f"Errors ({len(tract_errors)}):"); [print(f"  {e}") for e in tract_errors[:10]]

if "tract_fips" not in df_tracts_all.columns and all(c in df_tracts_all.columns for c in ["state","county","tract"]):
    df_tracts_all["tract_fips"] = df_tracts_all["state"].astype(str) + df_tracts_all["county"].astype(str) + df_tracts_all["tract"].astype(str)

df_tracts_latest = df_tracts_all[df_tracts_all["year"] == latest_year].copy()
print(f"\n--- Tract-Level: {len(df_tracts_all):,} rows x {len(df_tracts_all.columns)} cols ---")
print(f"Years: {int(df_tracts_all['year'].min())}-{int(df_tracts_all['year'].max())} | Tracts/yr: ~{len(df_tracts_latest):,}")

In [ ]:
# ---- Section 4b: TIGER/Line Tract Shapefiles + Spatial Join ----
tiger_parquet = os.path.join(PROCESSED_DIR, "tiger_tracts.parquet")

if os.path.isfile(tiger_parquet):
    print(f"Loading cached: {tiger_parquet}")
    tracts_gdf = gpd.read_parquet(tiger_parquet)
else:
    tiger_year = "2024"
    tiger_base_url = f"https://www2.census.gov/geo/tiger/TIGER{tiger_year}/TRACT"
    tiger_dir = os.path.join(RAW_DIR, "tiger")
    os.makedirs(tiger_dir, exist_ok=True)
    all_tract_gdfs, tiger_errors = [], []
    print(f"Downloading TIGER/Line {tiger_year} tract shapefiles for {len(ALL_STATE_FIPS)} states...")
    for idx, st in enumerate(ALL_STATE_FIPS):
        fname = f"tl_{tiger_year}_{st}_tract.zip"
        local_zip = os.path.join(tiger_dir, fname)
        url = f"{tiger_base_url}/{fname}"
        if not os.path.isfile(local_zip):
            try:
                r = requests.get(url, stream=True, timeout=120)
                r.raise_for_status()
                with open(local_zip, "wb") as f:
                    for chunk in r.iter_content(chunk_size=65536):
                        f.write(chunk)
            except Exception as e:
                tiger_errors.append(f"State {st}: {e}")
                continue
        try:
            gdf = gpd.read_file(f"zip://{local_zip}")
            keep_cols = [c for c in ["STATEFP","COUNTYFP","TRACTCE","GEOID","NAMELSAD",
                                      "ALAND","AWATER","INTPTLAT","INTPTLON","geometry"] if c in gdf.columns]
            all_tract_gdfs.append(gdf[keep_cols])
        except Exception as e:
            tiger_errors.append(f"State {st}: read error - {e}")
        if (idx + 1) % 10 == 0:
            print(f"  Loaded {idx + 1}/{len(ALL_STATE_FIPS)} states...")

    tracts_gdf = gpd.GeoDataFrame(pd.concat(all_tract_gdfs, ignore_index=True)).to_crs("EPSG:4326")
    tracts_gdf.to_parquet(tiger_parquet, index=False)
    print(f"Saved: {tiger_parquet} ({os.path.getsize(tiger_parquet)/1024/1024:.0f} MB)")

print(f"\n--- TIGER/Line: {len(tracts_gdf):,} tracts, {tracts_gdf['STATEFP'].nunique()} states ---")

def geocode_bulk(df_input, lat_col="lat", lon_col="lon", tracts=tracts_gdf):
    """Spatial join: assign FIPS tract to every row with lat/lon coordinates."""
    gdf = gpd.GeoDataFrame(df_input, geometry=gpd.points_from_xy(df_input[lon_col], df_input[lat_col]), crs="EPSG:4326")
    result = gpd.sjoin(gdf, tracts[["STATEFP","COUNTYFP","TRACTCE","GEOID","geometry"]], how="left", predicate="within")
    result = result.rename(columns={"STATEFP": "state_fips", "COUNTYFP": "county_fips",
                                     "TRACTCE": "tract", "GEOID": "geoid"})
    return result.drop(columns=["geometry", "index_right"], errors="ignore")

print("geocode_bulk() function available for coordinate-to-tract lookups")

In [ ]:
# ---- Section 4c: FHFA HPI (Tract Level) ----
fhfa_tract_path = os.path.join(PROCESSED_DIR, "fhfa_hpi_tract.parquet")

if os.path.isfile(fhfa_tract_path):
    print(f"Loading cached: {fhfa_tract_path}")
    df_hpi_tract = pd.read_parquet(fhfa_tract_path)
else:
    fhfa_urls = [
        "https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_AT_BDL_tract.csv",
        "https://www.fhfa.gov/hpi/download/monthly/hpi_at_bdl_tract.csv",
    ]
    df_hpi_tract = pd.DataFrame()
    for url in fhfa_urls:
        try:
            df_hpi_tract = pd.read_csv(url, dtype=str)
            if len(df_hpi_tract) > 0:
                print(f"  [OK] FHFA tract HPI: {len(df_hpi_tract):,} rows from {url}")
                break
        except Exception as e:
            print(f"  [SKIP] {url}: {e}")
    if len(df_hpi_tract) > 0:
        df_hpi_tract.to_parquet(fhfa_tract_path, index=False)
        print(f"  Saved: {fhfa_tract_path}")
    else:
        print("  FHFA tract HPI: not available (URLs may have changed)")

print(f"FHFA Tract HPI: {len(df_hpi_tract):,} rows")

In [ ]:
# ---- Section 4d: OpenCelliD US Cell Towers ----
oci_processed_path = os.path.join(PROCESSED_DIR, "opencellid_us.parquet")

if os.path.isfile(oci_processed_path):
    print(f"Loading cached: {oci_processed_path}")
    df_towers = pd.read_parquet(oci_processed_path)
else:
    df_towers = pd.DataFrame()
    if not OPENCELLID_API_KEY:
        print("Set OPENCELLID_API_KEY in .env to download tower data")
    else:
        raw_dir_oci = os.path.join(RAW_DIR, "opencellid")
        os.makedirs(raw_dir_oci, exist_ok=True)
        gz_path = os.path.join(raw_dir_oci, "cell_towers.csv.gz")
        US_MCC_CODES = [310, 311, 312, 313, 316]
        if not os.path.isfile(gz_path):
            url = f"https://opencellid.org/ocid/downloads?token={OPENCELLID_API_KEY}&type=full&file=cell_towers.csv.gz"
            print("Downloading OpenCelliD bulk database (~500 MB)...")
            r_oci = requests.get(url, stream=True, timeout=600)
            r_oci.raise_for_status()
            with open(gz_path, "wb") as f:
                downloaded = 0
                for chunk in r_oci.iter_content(chunk_size=262144):
                    f.write(chunk)
                    downloaded += len(chunk)
                    if downloaded % (50 * 1024 * 1024) == 0:
                        print(f"  Downloaded {downloaded / 1024 / 1024:.0f} MB...")
            print(f"  Download complete: {os.path.getsize(gz_path)/1024/1024:.0f} MB")

        print(f"Filtering to US towers (MCC in {US_MCC_CODES})...")
        usecols = ["radio","mcc","net","area","cell","lon","lat","range","samples","changeable","created","updated"]
        us_frames = []
        total_read = 0
        for chunk in pd.read_csv(gz_path, compression="gzip", usecols=usecols,
                                  dtype={"mcc": "Int64", "net": "Int64", "area": "Int64", "cell": "Int64"},
                                  chunksize=500_000):
            total_read += len(chunk)
            us_chunk = chunk[chunk["mcc"].isin(US_MCC_CODES)]
            if len(us_chunk) > 0:
                us_frames.append(us_chunk)
            if total_read % 2_000_000 == 0:
                print(f"  Processed {total_read:,} rows ... {sum(len(f) for f in us_frames):,} US towers so far")
        df_towers = pd.concat(us_frames, ignore_index=True) if us_frames else pd.DataFrame()
        if len(df_towers) > 0:
            df_towers.to_parquet(oci_processed_path, index=False)
            print(f"  Saved {len(df_towers):,} US towers -> {oci_processed_path}")

if len(df_towers) > 0:
    if "lng" in df_towers.columns and "lon" not in df_towers.columns:
        df_towers.rename(columns={"lng": "lon"}, inplace=True)
    print(f"\n--- OpenCelliD US Cell Towers: {len(df_towers):,} ---")
    print(df_towers["radio"].value_counts().to_string())
else:
    print("No cell tower data available")

In [ ]:
# ---- Section 4e: OpenCelliD Tract-Level Aggregation ----
oci_agg_path = os.path.join(PROCESSED_DIR, "opencellid_tract_agg.parquet")

if os.path.isfile(oci_agg_path):
    print(f"Loading cached: {oci_agg_path}")
    oci_agg = pd.read_parquet(oci_agg_path)
elif len(df_towers) > 0 and len(tracts_gdf) > 0:
    from datetime import datetime as _dt
    gdf_towers = gpd.GeoDataFrame(
        df_towers, geometry=gpd.points_from_xy(df_towers["lon"], df_towers["lat"]), crs="EPSG:4326"
    )
    joined = gpd.sjoin(gdf_towers, tracts_gdf[["GEOID", "ALAND", "geometry"]], how="inner", predicate="within")
    joined.rename(columns={"GEOID": "tract_fips"}, inplace=True)

    vz_nets, att_nets, tmo_nets = {311}, {310}, {312}
    oci_agg = joined.groupby("tract_fips").agg(
        tower_count=("cell", "count"),
        lte_count=("radio", lambda x: (x == "LTE").sum()),
        nr_count=("radio", lambda x: (x == "NR").sum()),
        has_verizon=("net", lambda x: bool(set(x.dropna().astype(int)) & vz_nets)),
        has_att=("net", lambda x: bool(set(x.dropna().astype(int)) & att_nets)),
        has_tmobile=("net", lambda x: bool(set(x.dropna().astype(int)) & tmo_nets)),
        unique_carriers=("net", "nunique"),
    ).reset_index()

    land_area = tracts_gdf[["GEOID", "ALAND"]].rename(columns={"GEOID": "tract_fips"})
    land_area["ALAND"] = pd.to_numeric(land_area["ALAND"], errors="coerce")
    oci_agg = oci_agg.merge(land_area, on="tract_fips", how="left")
    oci_agg["tower_density_sqkm"] = oci_agg["tower_count"] / (oci_agg["ALAND"] / 1e6).replace(0, np.nan)
    oci_agg["pct_5g_nr"] = oci_agg["nr_count"] / oci_agg["tower_count"].replace(0, np.nan)
    oci_agg.to_parquet(oci_agg_path, index=False)
    print(f"Saved: {oci_agg_path} ({len(oci_agg):,} tracts with towers)")
else:
    oci_agg = pd.DataFrame()
    print("OpenCelliD aggregation skipped (no tower data or TIGER tracts)")

print(f"OpenCelliD tract aggregation: {len(oci_agg):,} tracts")

In [ ]:
# ---- Viz: Tract-Level Timeline (2015-2024) -- National Median of Key ACS Attributes ----
if len(df_tracts_all) > 0:
    key_attrs = ["median_income", "median_home_value", "median_rent",
                 "poverty_rate", "vacancy_rate", "college_degree_pct",
                 "labor_force_participation", "population"]
    avail = [a for a in key_attrs if a in df_tracts_all.columns]
    df_tr_ann = df_tracts_all.groupby("year")[avail].median().reset_index()
    n_cols = 4
    n_rows = (len(avail) + n_cols - 1) // n_cols
    fig = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=[a.replace("_", " ").title() for a in avail],
        shared_xaxes=True, vertical_spacing=0.14,
    )
    colors = px.colors.qualitative.D3
    for idx, attr in enumerate(avail):
        r, c = divmod(idx, n_cols)
        fig.add_trace(
            go.Scatter(x=df_tr_ann["year"], y=df_tr_ann[attr],
                       mode="lines+markers", name=attr.replace("_", " ").title(),
                       line=dict(color=colors[idx % len(colors)], width=2),
                       showlegend=False),
            row=r + 1, col=c + 1,
        )
    fig.update_layout(
        title="Census Tracts -- National Median Attribute Trends (2015-2024)",
        height=400 * n_rows, margin=dict(l=50, r=30, t=80, b=40),
    )
    fig.update_xaxes(dtick=2)
    fig.show()
else:
    print("No tract data for timeline visualization")

---
## 5. ZCTA (ZIP Code) Level -- ACS + Gazetteer + FHFA HPI ZIP

**Source**: Census ACS 5-year (35+13 vars), Census Gazetteer (lat/lon centroids), FHFA HPI (ZIP-level)
**Fetch**: ACS -- 1 call per year. Gazetteer -- 1 file download. FHFA -- CSV download.
**Join key**: `zcta` (5-digit ZIP)

ZCTA is a separate geography -- it does NOT nest inside the state/county/tract hierarchy.

In [ ]:
# ---- Section 5a: ZCTA-Level ACS (2015-2024) ----
zcta_path = os.path.join(DATA_DIR, "census_zcta_demographics_2015_2024.parquet")

if os.path.isfile(zcta_path):
    print(f"Loading cached: {zcta_path}")
    df_zcta_all = pd.read_parquet(zcta_path)
else:
    all_zcta_frames, zcta_errors = [], []
    print(f"Fetching ZCTA-level: {len(YEARS)} years, 35 vars (three-batch)")
    for yr in YEARS:
        base_url = f"https://api.census.gov/data/{yr}/acs/{DATASET}"
        try:
            df_yr = fetch_census_three_batch(
                base_url, {"for": "zip code tabulation area:*"},
                CENSUS_API_KEY, RENAME_MAP, ["zip code tabulation area"],
                include_c24050=(yr >= 2012),
            )
            zcta_col = [c for c in df_yr.columns if "zip code" in c.lower() or "zcta" in c.lower()]
            df_yr.rename(columns={zcta_col[0] if zcta_col else df_yr.columns[-1]: "zcta"}, inplace=True)
            df_yr["year"] = yr
            df_yr = compute_fmv_derived(df_yr)
            all_zcta_frames.append(df_yr)
            print(f"  {yr}: {len(df_yr):,} ZCTAs")
        except Exception as e:
            zcta_errors.append(f"{yr}: {e}")
            print(f"  {yr}: ERROR - {e}")
        time.sleep(0.5)

    df_zcta_all = pd.concat(all_zcta_frames, ignore_index=True) if all_zcta_frames else pd.DataFrame()
    if len(df_zcta_all) > 0:
        df_zcta_all.to_parquet(zcta_path, index=False, engine="pyarrow")
        print(f"Saved: {zcta_path}")
    if zcta_errors:
        print(f"Errors: {zcta_errors}")

df_zcta = df_zcta_all[df_zcta_all["year"] == latest_year].copy() if len(df_zcta_all) > 0 else pd.DataFrame()
print(f"\n--- ZCTA-Level: {len(df_zcta_all):,} rows x {len(df_zcta_all.columns) if len(df_zcta_all) > 0 else 0} cols ---")
print(f"Years: {int(df_zcta_all['year'].min())}-{int(df_zcta_all['year'].max())} | ZCTAs/yr: ~{len(df_zcta):,}" if len(df_zcta_all) > 0 else "No ZCTA data")

In [ ]:
# ---- Section 5b: FHFA HPI (ZIP Level) ----
fhfa_zip_path = os.path.join(PROCESSED_DIR, "fhfa_hpi_zip.parquet")

if os.path.isfile(fhfa_zip_path):
    print(f"Loading cached: {fhfa_zip_path}")
    df_hpi_zip = pd.read_parquet(fhfa_zip_path)
else:
    fhfa_zip_urls = [
        "https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_AT_BDL_ZIP5.csv",
        "https://www.fhfa.gov/hpi/download/monthly/hpi_at_bdl_zip5.csv",
    ]
    df_hpi_zip = pd.DataFrame()
    for url in fhfa_zip_urls:
        try:
            df_hpi_zip = pd.read_csv(url, dtype=str)
            if len(df_hpi_zip) > 0:
                print(f"  [OK] FHFA ZIP HPI: {len(df_hpi_zip):,} rows from {url}")
                break
        except Exception as e:
            print(f"  [SKIP] {url}: {e}")
    if len(df_hpi_zip) > 0:
        df_hpi_zip.to_parquet(fhfa_zip_path, index=False)
    else:
        print("  FHFA ZIP HPI: not available")

print(f"FHFA ZIP HPI: {len(df_hpi_zip):,} rows")

In [ ]:
# ---- Section 5c: ZCTA Gazetteer Centroids ----
gaz_path = os.path.join(RAW_DIR, "2024_Gaz_zcta_national.txt")
df_gaz = None
if os.path.isfile(gaz_path):
    df_gaz = pd.read_csv(gaz_path, sep="\t", dtype=str)
else:
    gaz_url = "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2024_Gazetteer/2024_Gaz_zcta_national.zip"
    try:
        import zipfile, io as _io
        r = requests.get(gaz_url, timeout=60)
        r.raise_for_status()
        z = zipfile.ZipFile(_io.BytesIO(r.content))
        txt_name = [n for n in z.namelist() if n.endswith(".txt")][0]
        z.extract(txt_name, RAW_DIR)
        extracted = os.path.join(RAW_DIR, txt_name)
        if extracted != gaz_path:
            os.rename(extracted, gaz_path)
        df_gaz = pd.read_csv(gaz_path, sep="\t", dtype=str)
        print(f"Downloaded Gazetteer: {len(df_gaz)} ZCTAs with centroids")
    except Exception as e:
        print(f"Gazetteer download failed: {e}")

if df_gaz is not None and len(df_zcta) > 0:
    gaz_cols = df_gaz.columns.tolist()
    lat_col = next((c for c in gaz_cols if "lat" in c.lower()), None)
    lon_col = next((c for c in gaz_cols if "long" in c.lower() or "lon" in c.lower()), None)
    zcta_gaz_col = next((c for c in gaz_cols if "geoid" in c.lower() or "zcta" in c.lower()), gaz_cols[0])
    if lat_col and lon_col:
        df_gaz_slim = df_gaz[[zcta_gaz_col, lat_col, lon_col]].copy()
        df_gaz_slim.columns = ["zcta", "lat", "lon"]
        df_gaz_slim["lat"] = pd.to_numeric(df_gaz_slim["lat"], errors="coerce")
        df_gaz_slim["lon"] = pd.to_numeric(df_gaz_slim["lon"], errors="coerce")
        df_gaz_slim["zcta"] = df_gaz_slim["zcta"].astype(str).str.strip()
        print(f"Gazetteer centroids: {len(df_gaz_slim)} ZCTAs with lat/lon")
    else:
        df_gaz_slim = pd.DataFrame()
else:
    df_gaz_slim = pd.DataFrame()
    print("Gazetteer not available or no ZCTA data")

In [ ]:
# ---- Viz: ZCTA-Level Timeline (2015-2024) -- National Median of Key ACS Attributes ----
if len(df_zcta_all) > 0:
    key_attrs = ["median_income", "median_home_value", "median_rent",
                 "poverty_rate", "vacancy_rate", "college_degree_pct",
                 "labor_force_participation", "population"]
    avail = [a for a in key_attrs if a in df_zcta_all.columns]
    df_z_ann = df_zcta_all.groupby("year")[avail].median().reset_index()
    n_cols = 4
    n_rows = (len(avail) + n_cols - 1) // n_cols
    fig = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=[a.replace("_", " ").title() for a in avail],
        shared_xaxes=True, vertical_spacing=0.14,
    )
    colors = px.colors.qualitative.Bold
    for idx, attr in enumerate(avail):
        r, c = divmod(idx, n_cols)
        fig.add_trace(
            go.Scatter(x=df_z_ann["year"], y=df_z_ann[attr],
                       mode="lines+markers", name=attr.replace("_", " ").title(),
                       line=dict(color=colors[idx % len(colors)], width=2),
                       showlegend=False),
            row=r + 1, col=c + 1,
        )
    fig.update_layout(
        title="ZCTA (ZIP) Level -- National Median Attribute Trends (2015-2024)",
        height=400 * n_rows, margin=dict(l=50, r=30, t=80, b=40),
    )
    fig.update_xaxes(dtick=2)
    fig.show()
else:
    print("No ZCTA data for timeline visualization")

---
## 6. Block Group Level -- ACS Demographics (Latest Year)

**Source**: Census ACS 5-year (35+13 vars) -- finest ACS geography (~220,000 block groups)
**Fetch**: 52 states x 1 year = 52 calls
**Join key**: `bg_fips = state + county + tract + block_group`

In [ ]:
# ---- Section 6: Block Group Level ACS (latest year only) ----
bg_year = latest_year
bg_path = os.path.join(DATA_DIR, f"census_blockgroup_all_us_{bg_year}.parquet")

if os.path.isfile(bg_path):
    print(f"Loading cached: {bg_path}")
    df_blockgroups = pd.read_parquet(bg_path)
else:
    all_bg_frames, bg_errors = [], []
    base_url = f"https://api.census.gov/data/{bg_year}/acs/{DATASET}"
    print(f"Fetching block groups: {len(ALL_STATE_FIPS)} states, year {bg_year}, 35 vars")
    for idx, st in enumerate(ALL_STATE_FIPS):
        try:
            df_bg = fetch_census_three_batch(
                base_url, {"for": "block group:*", "in": f"state:{st}"},
                CENSUS_API_KEY, RENAME_MAP, ["state", "county", "tract", "block group"],
                include_c24050=True,
            )
            all_bg_frames.append(df_bg)
        except Exception as e:
            bg_errors.append(f"State {st}: {e}")
        if (idx + 1) % 10 == 0:
            n = sum(len(f) for f in all_bg_frames)
            print(f"  {idx+1}/{len(ALL_STATE_FIPS)} states ({n:,} BGs)")
        time.sleep(0.2)

    if all_bg_frames:
        df_blockgroups = pd.concat(all_bg_frames, ignore_index=True)
        bg_col = "block group" if "block group" in df_blockgroups.columns else df_blockgroups.columns[-1]
        df_blockgroups["bg_fips"] = df_blockgroups["state"] + df_blockgroups["county"] + df_blockgroups["tract"] + df_blockgroups[bg_col]
        df_blockgroups["tract_fips"] = df_blockgroups["state"] + df_blockgroups["county"] + df_blockgroups["tract"]
        df_blockgroups["county_fips"] = df_blockgroups["state"].astype(str).str.zfill(2) + df_blockgroups["county"].astype(str).str.zfill(3)
        df_blockgroups["year"] = bg_year
        df_blockgroups = compute_fmv_derived(df_blockgroups)
        df_blockgroups.to_parquet(bg_path, index=False, engine="pyarrow")
        print(f"Saved: {bg_path}")
        if bg_errors:
            print(f"Errors: {bg_errors[:3]}")
    else:
        df_blockgroups = pd.DataFrame()
        print("Block group fetch failed")

print(f"\n--- Block Group ({bg_year}): {len(df_blockgroups):,} rows x {len(df_blockgroups.columns)} cols ---")

In [ ]:
# ---- Viz: Block Group Level -- Attribute Distributions (Latest Year) ----
# Block groups only have a single year snapshot; show distributions.
if len(df_blockgroups) > 0:
    key_attrs = ["median_income", "median_home_value", "median_rent",
                 "poverty_rate", "vacancy_rate", "college_degree_pct"]
    avail = [a for a in key_attrs if a in df_blockgroups.columns]
    n_cols = 3
    n_rows = (len(avail) + n_cols - 1) // n_cols
    fig = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=[a.replace("_", " ").title() for a in avail],
    )
    colors = px.colors.qualitative.Pastel
    for idx, attr in enumerate(avail):
        r, c = divmod(idx, n_cols)
        vals = df_blockgroups[attr].dropna()
        p1, p99 = vals.quantile(0.01), vals.quantile(0.99)
        vals_clipped = vals.clip(p1, p99)
        fig.add_trace(
            go.Histogram(
                x=vals_clipped, nbinsx=60,
                name=attr.replace("_", " ").title(),
                marker_color=colors[idx % len(colors)],
                showlegend=False,
            ),
            row=r + 1, col=c + 1,
        )
    fig.update_layout(
        title=f"Block Groups -- Attribute Distributions ({bg_year}, 1st-99th pct)",
        height=350 * n_rows, margin=dict(l=50, r=30, t=80, b=40),
    )
    fig.show()
else:
    print("No block group data for visualization")

---
## 7. Block Level -- Decennial Census Population (2000 / 2010 / 2020)

**Source**: US Census Decennial Census (PL 94-171 Redistricting Data)
**Note**: ACS data is **not available** at the Block level. Only the Decennial Census (every 10 years) publishes block-level data.
**Available fields**: Population (P1_001N), Housing Units (H1_001N)
**Years**: 2020 (full national), 2010, 2000
**Scale**: ~8 million blocks nationally; sample of 5 large states fetched live.
**Join key**: `block_fips = state(2) + county(3) + tract(6) + block(4)` = 15-digit FIPS

In [ ]:
# ---- Section 7: Census Block Level -- Decennial Census 2020 (sample states) ----
# Full US: ~8M blocks. We sample the 5 most populous states for demonstration.
# To fetch all states, iterate over ALL_STATE_FIPS (will take ~30 min).
block_path = os.path.join(DATA_DIR, "census_block_population_2020_sample.parquet")
BLOCK_SAMPLE_STATES = ["06", "36", "48", "17", "12"]  # CA, NY, TX, IL, FL
BLOCK_SAMPLE_NAMES  = {"06": "CA", "36": "NY", "48": "TX", "17": "IL", "12": "FL"}

if os.path.isfile(block_path):
    print(f"Loading cached: {block_path}")
    df_blocks = pd.read_parquet(block_path)
else:
    block_frames, block_errors = [], []
    print("Fetching Decennial Census 2020 block-level population...")
    print("Sample states:", list(BLOCK_SAMPLE_NAMES.values()))
    for st in BLOCK_SAMPLE_STATES:
        try:
            url = "https://api.census.gov/data/2020/dec/pl"
            params = {
                "get": "P1_001N,H1_001N,NAME",
                "for": "block:*",
                "in": f"state:{st} county:*",
            }
            if CENSUS_API_KEY:
                params["key"] = CENSUS_API_KEY
            r = requests.get(url, params=params, timeout=180, verify=False)
            r.raise_for_status()
            data = r.json()
            df_b = pd.DataFrame(data[1:], columns=data[0])
            df_b["population"]     = pd.to_numeric(df_b["P1_001N"], errors="coerce")
            df_b["housing_units"]  = pd.to_numeric(df_b["H1_001N"], errors="coerce")
            df_b["year"]           = 2020
            df_b["state"]          = df_b["state"].astype(str).str.zfill(2)
            df_b["county"]         = df_b["county"].astype(str).str.zfill(3)
            df_b["tract"]          = df_b["tract"].astype(str).str.zfill(6)
            df_b["block"]          = df_b["block"].astype(str).str.zfill(4)
            df_b["block_fips"]     = df_b["state"] + df_b["county"] + df_b["tract"] + df_b["block"]
            df_b["county_fips"]    = df_b["state"] + df_b["county"]
            df_b["tract_fips"]     = df_b["state"] + df_b["county"] + df_b["tract"]
            block_frames.append(df_b)
            print(f"  State {BLOCK_SAMPLE_NAMES[st]} ({st}): {len(df_b):,} blocks")
        except Exception as e:
            block_errors.append(f"State {st}: {e}")
            print(f"  State {BLOCK_SAMPLE_NAMES[st]} ({st}): ERROR - {e}")
        time.sleep(0.5)

    if block_frames:
        df_blocks = pd.concat(block_frames, ignore_index=True)
        df_blocks.to_parquet(block_path, index=False, engine="pyarrow")
        print(f"\nSaved: {block_path} ({len(df_blocks):,} blocks)")
        if block_errors:
            print(f"Errors: {block_errors}")
    else:
        df_blocks = pd.DataFrame()
        print("Block data fetch failed")

print(f"\n--- Block Level (Decennial 2020): {len(df_blocks):,} rows x {len(df_blocks.columns)} cols ---")
if len(df_blocks) > 0:
    print(f"Columns: {list(df_blocks.columns)}")
    print(df_blocks[["state", "county", "tract", "block", "population", "housing_units"]].head(5))

In [ ]:
# ---- Viz: Block Level -- Population Distribution & State Summary (2020 Decennial Census) ----
if len(df_blocks) > 0:
    state_blk = df_blocks.groupby("state")["population"].agg(
        total_pop="sum", block_count="count", median_pop_per_block="median"
    ).reset_index()
    state_blk["state_name"] = state_blk["state"].map(FIPS_TO_ABBR)

    fig = make_subplots(
        rows=1, cols=2,
        subplot_titles=["Total Blocks per State", "Median Population per Block"],
    )
    fig.add_trace(
        go.Bar(x=state_blk["state_name"], y=state_blk["block_count"],
               name="Block Count", marker_color="#1f77b4"),
        row=1, col=1,
    )
    fig.add_trace(
        go.Bar(x=state_blk["state_name"], y=state_blk["median_pop_per_block"],
               name="Median Pop/Block", marker_color="#ff7f0e"),
        row=1, col=2,
    )
    fig.update_layout(
        title="Census Block Level -- State Summary (2020 Decennial Census, 5-state sample)",
        height=420, showlegend=False, margin=dict(l=50, r=30, t=70, b=40),
    )
    fig.show()

    # Population distribution histogram
    fig2 = go.Figure()
    pop_nonzero = df_blocks[df_blocks["population"] > 0]["population"].clip(upper=500)
    fig2.add_trace(go.Histogram(
        x=pop_nonzero, nbinsx=60, name="Population per Block",
        marker_color="#2ca02c",
    ))
    pct_zero = 100 * (df_blocks["population"] == 0).sum() / len(df_blocks)
    fig2.update_layout(
        title=f"Block Population Distribution (2020, pop > 0, capped at 500 | {pct_zero:.1f}% zero-pop blocks)",
        xaxis_title="Population per Block",
        yaxis_title="Number of Blocks",
        height=380, margin=dict(l=60, r=30, t=70, b=50),
    )
    fig2.show()
else:
    print("No block data available for visualization")

---
## 8. Temporal Trend Features -- Growth Rates from Panel Data

Compute **1-year, 3-year, and 5-year growth rates** for each tract from the 10-year Census ACS panel (2015-2024). Trends capture market momentum -- a tract with 30% income growth in 5 years is fundamentally different from one that stagnated.

In [ ]:
# ---- Section 8: Temporal Trend Features (Tract Level) ----
trends_path = os.path.join(PROCESSED_DIR, "temporal_trends_tract.parquet")

if os.path.isfile(trends_path):
    print(f"Loading cached: {trends_path}")
    df_trends = pd.read_parquet(trends_path)
elif len(df_tracts_all) > 0:
    lt_year = int(df_tracts_all["year"].max())
    trend_metrics = {
        "population": "population", "median_income": "median_income",
        "median_home_value": "median_home_value", "median_rent": "median_rent",
        "median_contract_rent": "median_contract_rent",
        "total_housing_units": "total_housing_units",
        "vacancy_rate": "vacancy_rate", "college_degree_pct": "college_degree_pct",
        "labor_force_participation": "labor_force_participation",
        "poverty_rate": "poverty_rate",
    }
    available = {k: v for k, v in trend_metrics.items() if v in df_tracts_all.columns}
    windows = {"1yr": 1, "3yr": 3, "5yr": 5}
    trend_series = []
    print(f"Computing trends for {len(available)} metrics | Latest: {lt_year}")
    for wname, yrs_back in windows.items():
        cmp_year = lt_year - yrs_back
        df_lt = df_tracts_all[df_tracts_all["year"] == lt_year].set_index("tract_fips")
        df_cmp = df_tracts_all[df_tracts_all["year"] == cmp_year].set_index("tract_fips")
        if len(df_cmp) == 0:
            continue
        for mname, col in available.items():
            if col not in df_lt.columns or col not in df_cmp.columns:
                continue
            lt_vals = pd.to_numeric(df_lt[col], errors="coerce")
            cmp_vals = pd.to_numeric(df_cmp[col], errors="coerce").reindex(lt_vals.index)
            denom = cmp_vals.where(cmp_vals.abs() > 1e-6, np.nan)
            growth = ((lt_vals - cmp_vals) / denom).clip(-0.9, 5.0)
            trend_series.append(growth.rename(f"{mname}_growth_{wname}"))

    if trend_series:
        df_trends = pd.concat(trend_series, axis=1).reset_index()
        df_trends.rename(columns={"index": "tract_fips"}, inplace=True)
        df_trends.to_parquet(trends_path, index=False)
        print(f"Saved: {trends_path} ({len(df_trends):,} tracts x {len(df_trends.columns)-1} features)")
    else:
        df_trends = pd.DataFrame()
else:
    df_trends = pd.DataFrame()
    print("Tract data not available for trends")

print(f"Temporal trends: {len(df_trends):,} tracts, {len(df_trends.columns)-1 if len(df_trends) > 0 else 0} features")

In [ ]:
# ---- FHFA HPI Appreciation Rates at ZIP Level ----
hpi_rates_path = os.path.join(PROCESSED_DIR, "fhfa_hpi_zip_rates.parquet")

if os.path.isfile(hpi_rates_path):
    print(f"Loading cached: {hpi_rates_path}")
    df_hpi_rates = pd.read_parquet(hpi_rates_path)
elif len(df_hpi_zip) > 0:
    yr_col = next((c for c in df_hpi_zip.columns if c.lower() in ("yr", "year")), None)
    hpi_col = next((c for c in df_hpi_zip.columns if "hpi" in c.lower() or "index" in c.lower()), None)
    place_col = next((c for c in df_hpi_zip.columns if "zip" in c.lower() or "place" in c.lower()), None)
    if yr_col and hpi_col and place_col:
        df_hpi_zip[yr_col] = pd.to_numeric(df_hpi_zip[yr_col], errors="coerce")
        df_hpi_zip[hpi_col] = pd.to_numeric(df_hpi_zip[hpi_col], errors="coerce")
        max_yr = int(df_hpi_zip[yr_col].max())
        hpi_appreciation = []
        for years_back, label in [(1, "1yr"), (3, "3yr"), (5, "5yr")]:
            latest = df_hpi_zip[df_hpi_zip[yr_col] == max_yr].set_index(place_col)[hpi_col]
            compare = df_hpi_zip[df_hpi_zip[yr_col] == max_yr - years_back].set_index(place_col)[hpi_col]
            rate = ((latest - compare.reindex(latest.index)) / compare.reindex(latest.index)).clip(-0.9, 5.0)
            hpi_appreciation.append(rate.rename(f"hpi_appreciation_{label}"))
        if hpi_appreciation:
            df_hpi_rates = pd.concat(hpi_appreciation, axis=1).reset_index()
            df_hpi_rates.rename(columns={place_col: "zip_code"}, inplace=True)
            df_hpi_rates.to_parquet(hpi_rates_path, index=False)
            print(f"Saved: {hpi_rates_path} ({len(df_hpi_rates):,} ZIPs)")
        else:
            df_hpi_rates = pd.DataFrame()
    else:
        df_hpi_rates = pd.DataFrame()
        print(f"Could not identify FHFA columns: yr={yr_col}, hpi={hpi_col}, place={place_col}")
else:
    df_hpi_rates = pd.DataFrame()
    print("FHFA ZIP data not available for appreciation rates")

print(f"FHFA HPI appreciation rates: {len(df_hpi_rates):,} ZIPs")

---
## 9. Hierarchical Missing Value Imputation

Fill Census-suppressed and structurally missing values using the geographic hierarchy:
- **Tracts** <- county median <- state median
- **Counties** <- state median
- **States** <- national median by year
- **ZCTA** <- national median by year (no geographic parent)
- **Block groups** <- tract <- county <- state
- **BLS counties** missing unemployment <- FRED state-level rate

Adds `imputed_{col}` boolean flags for ML transparency. Recomputes derived features after imputation.

In [ ]:
# ---- Section 9: Hierarchical Imputation ----

def impute_hierarchical(df, parent_agg, join_keys, fill_cols, imputed_prefix="imputed_"):
    """Fill missing values from parent aggregates. Add _imputed indicator columns."""
    if df is None or len(df) == 0 or parent_agg is None or len(parent_agg) == 0:
        return df
    out = df.copy()
    cols = [c for c in fill_cols if c in out.columns and c in parent_agg.columns]
    if not cols:
        return out
    parent = parent_agg[join_keys + cols].copy()
    parent = parent.rename(columns={c: f"_parent_{c}" for c in cols})
    merged = out.merge(parent, on=join_keys, how="left", suffixes=("", "_y"))
    for c in cols:
        pc = f"_parent_{c}"
        if pc not in merged.columns:
            continue
        mask = out[c].isna() & merged[pc].notna()
        if mask.any():
            out.loc[mask, c] = merged.loc[mask, pc].values
            flag_col = f"{imputed_prefix}{c}"
            if flag_col not in out.columns:
                out[flag_col] = False
            out.loc[mask, flag_col] = True
    return out

RAW_NUMERIC_COLS = RAW_FEATURE_NAMES

# 1) States: fill from national median by year
if len(df_states_all) > 0:
    for yr in df_states_all["year"].unique():
        mask = df_states_all["year"] == yr
        for c in [x for x in RAW_NUMERIC_COLS if x in df_states_all.columns]:
            national_median = df_states_all.loc[mask, c].median()
            if pd.notna(national_median):
                fill_mask = mask & df_states_all[c].isna()
                if fill_mask.any():
                    df_states_all.loc[fill_mask, c] = national_median
    df_states_all = compute_fmv_derived(df_states_all)
    print(f"[OK] States: imputed + derived | {len(df_states_all):,} rows")

# 2) Counties: fill from state aggregates
if len(df_counties_all) > 0 and len(df_states_all) > 0:
    state_agg = df_states_all.groupby(["state", "year"])[RAW_NUMERIC_COLS].median().reset_index()
    for c in [x for x in RAW_NUMERIC_COLS if x in df_counties_all.columns and x in state_agg.columns]:
        pc = f"_p_{c}"
        state_agg_c = state_agg[["state", "year", c]].rename(columns={c: pc})
        merged = df_counties_all.merge(state_agg_c, on=["state", "year"], how="left")
        m = df_counties_all[c].isna() & merged[pc].notna()
        if m.any():
            df_counties_all.loc[m, c] = merged.loc[m, pc].values
    df_counties_all = compute_fmv_derived(df_counties_all)
    print(f"[OK] Counties: imputed from state + derived | {len(df_counties_all):,} rows")

# 3) Tracts: fill from county, then state
if len(df_tracts_all) > 0 and len(df_counties_all) > 0:
    if "county_fips" not in df_tracts_all.columns:
        df_tracts_all["county_fips"] = df_tracts_all["state"].astype(str).str.zfill(2) + df_tracts_all["county"].astype(str).str.zfill(3)
    county_agg = df_counties_all.groupby(["county_fips", "year"])[RAW_NUMERIC_COLS].median().reset_index()
    df_tracts_all = impute_hierarchical(df_tracts_all, county_agg, ["county_fips", "year"], RAW_NUMERIC_COLS)
    state_agg2 = df_states_all.groupby(["state", "year"])[RAW_NUMERIC_COLS].median().reset_index()
    df_tracts_all = impute_hierarchical(df_tracts_all, state_agg2, ["state", "year"], RAW_NUMERIC_COLS)
    df_tracts_all = compute_fmv_derived(df_tracts_all)
    print(f"[OK] Tracts: county->state imputation + derived | {len(df_tracts_all):,} rows")

# 4) ZCTA: fill from national median by year
if len(df_zcta_all) > 0:
    for yr in df_zcta_all["year"].unique():
        mask = df_zcta_all["year"] == yr
        for c in [x for x in RAW_NUMERIC_COLS if x in df_zcta_all.columns]:
            national_median = df_zcta_all.loc[mask, c].median()
            if pd.notna(national_median):
                fill_mask = mask & df_zcta_all[c].isna()
                if fill_mask.any():
                    df_zcta_all.loc[fill_mask, c] = national_median
    df_zcta_all = compute_fmv_derived(df_zcta_all)
    print(f"[OK] ZCTA: national median fallback + derived | {len(df_zcta_all):,} rows")

# 5) BLS: fill missing counties with FRED state unemployment
if len(df_bls_cty_latest) > 0 and len(df_state_ur) > 0:
    try:
        abbr_to_fips = {v: k for k, v in FIPS_TO_ABBR.items()}
        fred_ur = df_state_ur.copy()
        fred_ur["state_fips"] = fred_ur["state_abbr"].map(abbr_to_fips)
        if "state_fips" not in df_bls_cty_latest.columns:
            df_bls_cty_latest["state_fips"] = df_bls_cty_latest["county_fips"].str[:2]
        missing = df_bls_cty_latest[df_bls_cty_latest["unemployment_rate"].isna()]
        if len(missing) > 0:
            merged = missing.merge(fred_ur[["state_fips", "unemployment_rate"]].rename(
                columns={"unemployment_rate": "ur_fred"}), on="state_fips", how="left")
            fill_mask = merged["ur_fred"].notna()
            if fill_mask.any():
                idx = merged.loc[fill_mask].index
                df_bls_cty_latest.loc[idx, "unemployment_rate"] = merged.loc[fill_mask, "ur_fred"].values
                print(f"[OK] BLS: filled {fill_mask.sum()} counties from FRED state unemployment")
    except Exception as e:
        print(f"[INFO] BLS-FRED proxy skipped: {e}")

# Refresh latest-year slices
df_states = df_states_all[df_states_all["year"] == latest_year].copy()
if len(df_counties_all) > 0:
    df_counties = df_counties_all[df_counties_all["year"] == latest_year].copy()
if len(df_tracts_all) > 0:
    df_tracts_latest = df_tracts_all[df_tracts_all["year"] == latest_year].copy()
if len(df_zcta_all) > 0:
    df_zcta = df_zcta_all[df_zcta_all["year"] == latest_year].copy()

print("\n--- Imputation complete. Use imputed_* columns as missingness indicators in ML. ---")

---
## 10. Summary -- Full Data Pipeline Inventory

In [ ]:
# ---- Section 10a: Cell Tower Lease Rent Index (Benchmark) ----
from io import StringIO

lease_index_path = os.path.join(PROCESSED_DIR, "cell_tower_lease_rent_index.parquet")
if os.path.isfile(lease_index_path):
    print(f"Loading cached: {lease_index_path}")
    df_lease_index = pd.read_parquet(lease_index_path)
else:
    lease_urls = [
        "https://www.celltowerleaseexperts.com/datasets/US-Cell-Tower-Lease-Rent-Rates-Index.csv",
        "https://www.celltowerai.com/dataset-files/us-cell-tower-leaes-rent-rates-index.csv",
    ]
    df_lease_index = pd.DataFrame()
    for url in lease_urls:
        try:
            r = requests.get(url, timeout=30, headers={"User-Agent": "Mozilla/5.0"})
            r.raise_for_status()
            df_lease_index = pd.read_csv(StringIO(r.text))
            if len(df_lease_index) > 0:
                break
        except Exception as e:
            print(f"  {url}: {e}")
    if len(df_lease_index) > 0:
        col_map = {c: c.lower().replace(" ", "_").replace("-", "_") for c in df_lease_index.columns}
        df_lease_index.rename(columns=col_map, inplace=True)
        df_lease_index.to_parquet(lease_index_path, index=False)
        print(f"Saved: {lease_index_path} ({len(df_lease_index)} rows)")
    else:
        print("Cell Tower Lease Rent Index: download failed")

print(f"Lease rent index: {len(df_lease_index):,} rows")

In [ ]:
# ---- Section 10b: Full Pipeline Summary ----
print("=" * 80)
print("  FULL DATA PIPELINE SUMMARY  (28 Raw + 8 Derived ACS features)")
print("=" * 80)

_safe = lambda name: globals().get(name, pd.DataFrame())
n_yr = lambda df: df["year"].nunique() if "year" in df.columns and len(df) > 0 else 0

_st   = _safe("df_states_all")
_cty  = _safe("df_counties_all")
_tr   = _safe("df_tracts_all")
_z    = _safe("df_zcta_all")
_bg   = _safe("df_blockgroups")
_bls  = _safe("df_bls_county")
_trnd = _safe("df_trends")
_oci  = _safe("oci_agg")
_tgr  = globals().get("tracts_gdf", pd.DataFrame())
_fred = _safe("df_fred_national")
_tw   = _safe("df_towers")

print(f"\n  Source                   | Level          | Records       | Time      | Features")
print(f"  -------------------------+----------------+---------------+-----------+---------")
print(f"  FRED                     | National       | {len(_fred):>12,} | monthly   | macro")
print(f"  Census ACS               | State          | {len(_st):>12,} | {n_yr(_st)} years   | 35+13")
print(f"  FRED State UR            | State          | {len(df_state_ur):>12,} | latest    | 1")
print(f"  Census ACS               | County         | {len(_cty):>12,} | {n_yr(_cty)} years   | 35+13")
print(f"  BLS LAUS                 | County unemp.  | {len(_bls):>12,} | monthly   | 1")
print(f"  Census ACS               | Tract (ALL US) | {len(_tr):>12,} | {n_yr(_tr)} years   | 35+13")
print(f"  TIGER/Line               | Tract polygons | {len(_tgr):>12,} | -         | geom")
print(f"  FHFA HPI                 | Tract          | {len(_safe('df_hpi_tract')):>12,} | quarterly | HPI")
print(f"  OpenCelliD (bulk)        | Lat/Lon        | {len(_tw):>12,} | current   | towers")
print(f"  OpenCelliD (tract agg)   | Tract          | {len(_oci):>12,} | current   | density")
print(f"  Census ACS               | Block Group    | {len(_bg):>12,} | latest yr | 35+13")
print(f"  Census ACS               | ZCTA (ZIP)     | {len(_z):>12,} | {n_yr(_z)} years   | 35+13")
print(f"  FHFA HPI                 | ZIP            | {len(_safe('df_hpi_zip')):>12,} | quarterly | HPI")
print(f"  Temporal Trends          | Tract          | {len(_trnd):>12,} | 1/3/5yr   | {len(_trnd.columns)-1 if len(_trnd) > 0 else 0}")
print(f"  Lease Rent Index         | State/City     | {len(_safe('df_lease_index')):>12,} | benchmark | rent")

print(f"\n  GEOGRAPHIC HIERARCHY:")
print(f"    Nation (FRED) > State (ACS/FRED) > County (BLS/ACS) > Tract (ACS/FHFA/OCI/Trends) > Block Group (ACS)")
print(f"    ZCTA (ACS/FHFA) -- separate geography, does not nest in hierarchy")

print(f"\n  RAW CENSUS FEATURES (28):")
for i in range(0, len(RAW_FEATURE_NAMES), 4):
    chunk = RAW_FEATURE_NAMES[i:i+4]
    print(f"    {', '.join(chunk)}")

print(f"\n  DERIVED FEATURES (8):")
print(f"    {', '.join(DERIVED_FEATURE_NAMES)}")

print("\n" + "=" * 80)
print("  Pipeline complete. All cached files are in data/ and data/processed/.")
print("=" * 80)

---
## 11. Backfill 2015-2016 State Data & Multi-Level Choropleth Visualizations

The original Section 2 fetch failed for 2015-2016 because batch C variables
(`B28002_004E`, `B28002_013E`, `B07001_017E`) are not in the 2015/2016 ACS 5-year API.
This section re-fetches those two years with a reduced variable list, then merges them
into the existing 2017-2024 state panel so all choropleths can span **2015-2024**.

### Visualization hierarchy
| Level | Geography | Variables | Animation |
|-------|-----------|-----------|-----------|
| **State** | 52 states/territories | 35 raw + 13 derived | Year slider (2015-2024) |
| **County** | ~3,200 counties | Income, rent, vacancy, etc. | Year slider (2015-2024) |
| **ZCTA (ZIP)** | ~33,000 ZCTAs | Income, rent, broadband | Year slider (2015-2024) |
| **Tract** | ~85,000 tracts | Income, rent, vacancy, density | Year slider (2015-2024) |

**FRED Macro** indicators: 2005-present (national + state-level trends).

In [ ]:
# ---- 11a: Helper — FIPS-to-abbreviation mapping for state choropleths ----

FIPS_TO_ABBR = {
    "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA",
    "08": "CO", "09": "CT", "10": "DE", "11": "DC", "12": "FL",
    "13": "GA", "15": "HI", "16": "ID", "17": "IL", "18": "IN",
    "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME",
    "24": "MD", "25": "MA", "26": "MI", "27": "MN", "28": "MS",
    "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
    "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
    "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI",
    "45": "SC", "46": "SD", "47": "TN", "48": "TX", "49": "UT",
    "50": "VT", "51": "VA", "53": "WA", "54": "WV", "55": "WI",
    "56": "WY", "72": "PR",
}

CHOROPLETH_VARS = {
    "Census Micro (Demographics)": {
        "median_income":        {"title": "Median Household Income",    "fmt": "$,.0f", "cscale": "Viridis"},
        "per_capita_income":    {"title": "Per Capita Income",          "fmt": "$,.0f", "cscale": "Viridis"},
        "median_age":           {"title": "Median Age",                 "fmt": ".1f",   "cscale": "RdYlBu_r"},
        "population":           {"title": "Total Population",           "fmt": ",.0f",  "cscale": "YlOrRd"},
    },
    "Census Micro (Housing & Rent)": {
        "median_home_value":    {"title": "Median Home Value",          "fmt": "$,.0f", "cscale": "Plasma"},
        "median_rent":          {"title": "Median Gross Rent",          "fmt": "$,.0f", "cscale": "Inferno"},
        "rent_burden_pct":      {"title": "Rent Burden (%)",            "fmt": ".1f",   "cscale": "Reds"},
        "median_monthly_housing_cost": {"title": "Median Monthly Housing Cost", "fmt": "$,.0f", "cscale": "Magma"},
    },
    "Derived FMV Features": {
        "vacancy_rate":         {"title": "Vacancy Rate",               "fmt": ".1%",   "cscale": "RdYlGn_r"},
        "owner_renter_ratio":   {"title": "Owner-to-Renter Ratio",     "fmt": ".2f",   "cscale": "RdBu"},
        "broadband_penetration":{"title": "Broadband Penetration (%)", "fmt": ".1f",   "cscale": "Blues"},
        "rental_market_tightness": {"title": "Rental Market Tightness","fmt": ".3f",   "cscale": "YlOrRd"},
    },
    "Growth & Economic Activity": {
        "in_migration_rate":    {"title": "In-Migration Rate (%)",     "fmt": ".2f",   "cscale": "Greens"},
        "new_construction_rate":{"title": "New Construction Rate (%)", "fmt": ".2f",   "cscale": "Oranges"},
        "labor_force_participation": {"title": "Labor Force Part. (%)", "fmt": ".1f",  "cscale": "Tealgrn"},
        "college_degree_pct":   {"title": "College Degree (%)",        "fmt": ".1f",   "cscale": "Purples"},
    },
    "Income Inequality & Structure": {
        "poverty_rate":         {"title": "Poverty Rate (%)",           "fmt": ".1f",   "cscale": "OrRd"},
        "income_polarization":  {"title": "Income Polarization",       "fmt": ".2f",   "cscale": "Spectral_r"},
        "professional_employment_pct": {"title": "Professional Employment (%)", "fmt": ".1f", "cscale": "Teal"},
        "multifamily_pct":      {"title": "Multifamily Housing (%)",   "fmt": ".1f",   "cscale": "Purpor"},
    },
}

print(f"Configured {sum(len(v) for v in CHOROPLETH_VARS.values())} variables across {len(CHOROPLETH_VARS)} thematic groups")

### 11b. Backfill 2015-2016 + State-Level Choropleths (2015-2024)

Re-fetch the missing 2015-2016 state ACS data (excluding the variables that were
not yet published in those vintages), then render animated choropleths across all
52 states spanning the full **2015-2024** decade.

In [ ]:
# ---- 11b: Load state data + backfill missing years if needed ----

state_csv = os.path.join(DATA_DIR, "census_state_demographics_2015_2024.csv")
df_st = pd.read_csv(state_csv, dtype={"state": str})
existing_years = set(df_st["year"].unique())
missing_years = sorted(set(YEARS) - existing_years)

if missing_years:
    print(f"Backfilling missing years: {missing_years}")
    print("  (fetch_census_three_batch now handles per-variable fallback for older vintages)")
    backfill_frames = []
    for yr in missing_years:
        base_url = f"https://api.census.gov/data/{yr}/acs/{DATASET}"
        try:
            df_yr = fetch_census_three_batch(
                base_url, {"for": "state:*"}, CENSUS_API_KEY,
                RENAME_MAP, ["state"], include_c24050=(yr >= 2012),
            )
            df_yr["year"] = yr
            df_yr = compute_fmv_derived(df_yr)
            backfill_frames.append(df_yr)
            print(f"  {yr}: {len(df_yr)} states [OK]")
        except Exception as e:
            print(f"  {yr}: ERROR - {e}")
        time.sleep(0.3)

    if backfill_frames:
        df_backfill = pd.concat(backfill_frames, ignore_index=True)
        df_st = pd.concat([df_backfill, df_st], ignore_index=True)
        df_st = df_st.sort_values(["year", "state"]).reset_index(drop=True)
        df_st.to_csv(state_csv, index=False)
        print(f"Updated: {state_csv} ({len(df_st):,} rows)")
else:
    print(f"All years present: {sorted(existing_years)}")

df_st["state_abbr"] = df_st["state"].astype(str).str.zfill(2).map(FIPS_TO_ABBR)
df_st = df_st.dropna(subset=["state_abbr"])
years_sorted = sorted(df_st["year"].unique())
yr_min, yr_max = int(years_sorted[0]), int(years_sorted[-1])
print(f"\nState data: {len(df_st):,} rows | years: {yr_min}-{yr_max} ({len(years_sorted)} vintages) | states: {df_st['state_abbr'].nunique()}")

# ---- Animated choropleths by thematic group ----
for group_name, var_dict in CHOROPLETH_VARS.items():
    avail_vars = {k: v for k, v in var_dict.items() if k in df_st.columns}
    if not avail_vars:
        continue

    n_vars = len(avail_vars)
    fig = make_subplots(
        rows=1, cols=n_vars,
        subplot_titles=[cfg["title"] for cfg in avail_vars.values()],
        specs=[[{"type": "choropleth"}] * n_vars],
        horizontal_spacing=0.02,
    )

    df_latest = df_st[df_st["year"] == yr_max]
    for col_idx, (var_name, cfg) in enumerate(avail_vars.items(), 1):
        fig.add_trace(
            go.Choropleth(
                locations=df_latest["state_abbr"], z=df_latest[var_name],
                locationmode="USA-states", colorscale=cfg["cscale"],
                colorbar=dict(title=dict(text=cfg["title"].split("(")[0].strip(), font=dict(size=10)),
                              len=0.8, thickness=12, x=col_idx / n_vars - 0.01),
                hovertemplate=f"<b>%{{location}}</b><br>{cfg['title']}: %{{z:{cfg['fmt']}}}<extra></extra>",
                name=cfg["title"],
            ),
            row=1, col=col_idx,
        )

    frames = []
    for yr in years_sorted:
        df_yr = df_st[df_st["year"] == yr]
        frame_data = [
            go.Choropleth(
                locations=df_yr["state_abbr"], z=df_yr[var_name],
                locationmode="USA-states", colorscale=cfg["cscale"],
                hovertemplate=f"<b>%{{location}}</b><br>{cfg['title']}: %{{z:{cfg['fmt']}}}<extra></extra>",
            )
            for var_name, cfg in avail_vars.items()
        ]
        frames.append(go.Frame(data=frame_data, name=str(int(yr))))

    sliders = [dict(
        active=len(years_sorted) - 1,
        currentvalue={"prefix": "Year: ", "font": {"size": 14}},
        pad={"t": 30},
        steps=[dict(args=[[str(int(yr))], {"frame": {"duration": 500}, "mode": "immediate"}],
                     label=str(int(yr)), method="animate") for yr in years_sorted],
    )]

    fig.update_layout(
        title=dict(text=f"State Level \u2014 {group_name} ({yr_min}-{yr_max})", font=dict(size=16)),
        geo=dict(scope="usa", showlakes=True, lakecolor="rgb(200,220,255)"),
        height=420, margin=dict(l=10, r=10, t=80, b=30),
        sliders=sliders,
        updatemenus=[dict(
            type="buttons", showactive=False, x=0.05, y=-0.05,
            buttons=[
                dict(label="Play", method="animate",
                     args=[None, {"frame": {"duration": 800}, "fromcurrent": True}]),
                dict(label="Pause", method="animate",
                     args=[[None], {"frame": {"duration": 0}, "mode": "immediate"}]),
            ],
        )],
    )
    fig.frames = frames
    for i in range(1, n_vars + 1):
        fig.update_layout(**{f"geo{i if i > 1 else ''}": dict(scope="usa", showlakes=True)})
    fig.show()
    print(f"  {group_name}: {n_vars} maps")

In [ ]:
# ---- 11b (cont): Individual full-size animated choropleths for key FMV variables ----

KEY_STATE_VARS = [
    ("median_income",          "Median Household Income by State", "$,.0f", "Viridis"),
    ("median_home_value",      "Median Home Value by State",       "$,.0f", "Plasma"),
    ("median_rent",            "Median Gross Rent by State",       "$,.0f", "Inferno"),
    ("vacancy_rate",           "Vacancy Rate by State",            ".1%",   "RdYlGn_r"),
    ("broadband_penetration",  "Broadband Penetration (%) by State", ".1f", "Blues"),
    ("rental_market_tightness","Rental Market Tightness by State", ".3f",   "YlOrRd"),
    ("in_migration_rate",      "In-Migration Rate (%) by State",   ".2f",   "Greens"),
    ("poverty_rate",           "Poverty Rate (%) by State",        ".1f",   "OrRd"),
    ("income_polarization",    "Income Polarization by State",     ".2f",   "Spectral_r"),
    ("college_degree_pct",     "College Degree (%) by State",      ".1f",   "Purples"),
]

for var_name, title, fmt, cscale in KEY_STATE_VARS:
    if var_name not in df_st.columns:
        print(f"  SKIP {var_name} -- not in data")
        continue

    df_latest = df_st[df_st["year"] == yr_max]

    fig = go.Figure(
        go.Choropleth(
            locations=df_latest["state_abbr"], z=df_latest[var_name],
            locationmode="USA-states", colorscale=cscale,
            colorbar=dict(title=title.split(" by ")[0], thickness=15),
            hovertext=df_latest["NAME"],
            hovertemplate=f"<b>%{{hovertext}}</b><br>{title.split(' by')[0]}: %{{z:{fmt}}}<extra></extra>",
        )
    )

    frames = [
        go.Frame(
            data=[go.Choropleth(
                locations=df_st[df_st["year"] == yr]["state_abbr"],
                z=df_st[df_st["year"] == yr][var_name],
                locationmode="USA-states", colorscale=cscale,
                hovertext=df_st[df_st["year"] == yr]["NAME"],
                hovertemplate=f"<b>%{{hovertext}}</b><br>{title.split(' by')[0]}: %{{z:{fmt}}}<extra></extra>",
            )],
            name=str(int(yr)),
        )
        for yr in years_sorted
    ]

    sliders = [dict(
        active=len(years_sorted) - 1,
        currentvalue={"prefix": "Year: ", "font": {"size": 14}},
        pad={"t": 50},
        steps=[dict(args=[[str(int(yr))], {"frame": {"duration": 500}, "mode": "immediate"}],
                     label=str(int(yr)), method="animate") for yr in years_sorted],
    )]

    fig.update_layout(
        title=dict(text=f"{title} \u2014 Evolution ({yr_min}-{yr_max})", font=dict(size=15)),
        geo=dict(scope="usa", showlakes=True, lakecolor="rgb(200,220,255)",
                 projection=dict(type="albers usa")),
        height=500, margin=dict(l=10, r=10, t=80, b=30),
        sliders=sliders,
        updatemenus=[dict(
            type="buttons", showactive=False, x=0.05, y=-0.02,
            buttons=[
                dict(label="Play", method="animate",
                     args=[None, {"frame": {"duration": 800}, "fromcurrent": True}]),
                dict(label="Pause", method="animate",
                     args=[[None], {"frame": {"duration": 0}, "mode": "immediate"}]),
            ],
        )],
    )
    fig.frames = frames
    fig.show()

print(f"\n--- State-Level: {len(KEY_STATE_VARS)} animated choropleths ({yr_min}-{yr_max}) ---")

### 11c. County-Level Choropleths (2015-2024)

County-level choropleths using the Plotly counties GeoJSON (~3,200 counties).
Each county is identified by its 5-digit FIPS code (`state + county`).
If cached county data is not available, it is fetched live from Census ACS API.

In [ ]:
# ---- 11c: COUNTY-LEVEL ANIMATED CHOROPLETHS ----

county_path = os.path.join(DATA_DIR, "census_county_demographics_2015_2024.csv")

if os.path.isfile(county_path):
    print(f"Loading cached: {county_path}")
    df_co = pd.read_csv(county_path, dtype={"state": str, "county": str})
else:
    print("County data not cached. Fetching from Census ACS API...")
    co_frames, co_errors = [], []
    for yr in YEARS:
        base_url = f"https://api.census.gov/data/{yr}/acs/{DATASET}"
        try:
            df_yr = fetch_census_three_batch(
                base_url, {"for": "county:*", "in": "state:*"},
                CENSUS_API_KEY, RENAME_MAP, ["state", "county"],
                include_c24050=(yr >= 2012),
            )
            df_yr["year"] = yr
            df_yr = compute_fmv_derived(df_yr)
            co_frames.append(df_yr)
            print(f"  {yr}: {len(df_yr):,} counties [OK]")
        except Exception as e:
            co_errors.append(f"{yr}: {e}")
            print(f"  {yr}: ERROR - {e}")
        time.sleep(0.3)
    df_co = pd.concat(co_frames, ignore_index=True) if co_frames else pd.DataFrame()
    if len(df_co) > 0:
        df_co.to_csv(county_path, index=False)
        print(f"Saved: {county_path} ({len(df_co):,} rows)")

if len(df_co) > 0:
    df_co["state"] = df_co["state"].astype(str).str.zfill(2)
    df_co["county"] = df_co["county"].astype(str).str.zfill(3)
    df_co["county_fips"] = df_co["state"] + df_co["county"]
    co_years = sorted(df_co["year"].unique())
    co_yr_min, co_yr_max = int(co_years[0]), int(co_years[-1])
    print(f"County data: {len(df_co):,} rows | years: {co_yr_min}-{co_yr_max} | counties: {df_co['county_fips'].nunique():,}")
else:
    co_years = []
    print("No county data available")

In [ ]:
# ---- 11c (cont): County choropleth maps ----

if len(df_co) > 0:
    counties_geojson_url = "https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json"
    try:
        counties_geojson = requests.get(counties_geojson_url, timeout=30).json()
        print(f"County GeoJSON loaded: {len(counties_geojson['features']):,} features")
    except Exception as e:
        counties_geojson = None
        print(f"GeoJSON download failed: {e}")

    COUNTY_VARS = [
        ("median_income",        "Median Household Income", "$,.0f", "Viridis"),
        ("median_home_value",    "Median Home Value",       "$,.0f", "Plasma"),
        ("median_rent",          "Median Gross Rent",       "$,.0f", "Inferno"),
        ("vacancy_rate",         "Vacancy Rate",            ".1%",   "RdYlGn_r"),
        ("poverty_rate",         "Poverty Rate (%)",        ".1f",   "OrRd"),
        ("broadband_penetration","Broadband (%)",           ".1f",   "Blues"),
        ("in_migration_rate",    "In-Migration Rate (%)",   ".2f",   "Greens"),
        ("college_degree_pct",   "College Degree (%)",      ".1f",   "Purples"),
    ]

    if counties_geojson:
        for var_name, title, fmt, cscale in COUNTY_VARS:
            if var_name not in df_co.columns:
                continue

            df_latest = df_co[df_co["year"] == co_yr_max].copy()

            fig = go.Figure(go.Choropleth(
                geojson=counties_geojson,
                locations=df_latest["county_fips"],
                z=df_latest[var_name],
                colorscale=cscale,
                colorbar=dict(title=title, thickness=15),
                hovertext=df_latest.get("NAME", df_latest["county_fips"]),
                hovertemplate=f"<b>%{{hovertext}}</b><br>{title}: %{{z:{fmt}}}<extra></extra>",
                marker_line_width=0.1, marker_line_color="white",
            ))

            frames = [
                go.Frame(
                    data=[go.Choropleth(
                        geojson=counties_geojson,
                        locations=df_co[df_co["year"] == yr]["county_fips"],
                        z=df_co[df_co["year"] == yr][var_name],
                        colorscale=cscale,
                        hovertext=df_co[df_co["year"] == yr].get("NAME", df_co[df_co["year"] == yr]["county_fips"]),
                        hovertemplate=f"<b>%{{hovertext}}</b><br>{title}: %{{z:{fmt}}}<extra></extra>",
                        marker_line_width=0.1,
                    )],
                    name=str(int(yr)),
                )
                for yr in co_years
            ]

            sliders = [dict(
                active=len(co_years) - 1,
                currentvalue={"prefix": "Year: ", "font": {"size": 14}},
                pad={"t": 50},
                steps=[dict(args=[[str(int(yr))], {"frame": {"duration": 500}, "mode": "immediate"}],
                             label=str(int(yr)), method="animate") for yr in co_years],
            )]

            fig.update_layout(
                title=dict(text=f"County Level \u2014 {title} ({co_yr_min}-{co_yr_max})", font=dict(size=15)),
                geo=dict(scope="usa", showlakes=True, lakecolor="rgb(200,220,255)",
                         projection=dict(type="albers usa")),
                height=550, margin=dict(l=10, r=10, t=80, b=30),
                sliders=sliders,
                updatemenus=[dict(
                    type="buttons", showactive=False, x=0.05, y=-0.02,
                    buttons=[
                        dict(label="Play", method="animate",
                             args=[None, {"frame": {"duration": 800}, "fromcurrent": True}]),
                        dict(label="Pause", method="animate",
                             args=[[None], {"frame": {"duration": 0}, "mode": "immediate"}]),
                    ],
                )],
            )
            fig.frames = frames
            fig.show()
            print(f"  County: {title}")

        print(f"\n--- County-Level: {len(COUNTY_VARS)} animated choropleths ({co_yr_min}-{co_yr_max}) ---")
else:
    print("No county data for choropleth visualization")

### 11d. ZCTA (ZIP Code) Level Visualizations (2015-2024)

ZCTAs do **not** nest inside the state/county/tract hierarchy. Choropleth maps at the
ZIP level require a ZCTA-to-centroid mapping (from the Census Gazetteer). Since Plotly
does not have a native ZCTA GeoJSON, we use **scatter-geo density maps** (one dot per ZCTA,
colored by variable value) which render faster than polygon-based choropleths for ~33k ZCTAs.

In [ ]:
# ---- 11d: ZCTA (ZIP) LEVEL SCATTER-GEO DENSITY MAPS ----

zcta_path = os.path.join(DATA_DIR, "census_zcta_demographics_2015_2024.parquet")
gaz_path = os.path.join(RAW_DIR, "2024_Gaz_zcta_national.txt")

if os.path.isfile(zcta_path):
    print(f"Loading cached: {zcta_path}")
    df_zcta = pd.read_parquet(zcta_path)
else:
    print("ZCTA data not cached. Fetching from Census ACS API...")
    zcta_frames = []
    for yr in YEARS:
        base_url = f"https://api.census.gov/data/{yr}/acs/{DATASET}"
        try:
            df_yr = fetch_census_three_batch(
                base_url, {"for": "zip code tabulation area:*"},
                CENSUS_API_KEY, RENAME_MAP,
                ["zip code tabulation area"],
                include_c24050=(yr >= 2012),
            )
            df_yr["year"] = yr
            df_yr.rename(columns={"zip code tabulation area": "zcta"}, inplace=True)
            df_yr = compute_fmv_derived(df_yr)
            zcta_frames.append(df_yr)
            print(f"  {yr}: {len(df_yr):,} ZCTAs [OK]")
        except Exception as e:
            print(f"  {yr}: ERROR - {e}")
        time.sleep(0.3)
    df_zcta = pd.concat(zcta_frames, ignore_index=True) if zcta_frames else pd.DataFrame()
    if len(df_zcta) > 0:
        df_zcta.to_parquet(zcta_path, index=False)
        print(f"Saved: {zcta_path} ({len(df_zcta):,} rows)")

# Load or download Gazetteer centroids for lat/lon
df_gaz_slim = pd.DataFrame()
if os.path.isfile(gaz_path):
    df_gaz = pd.read_csv(gaz_path, sep="\t", dtype=str)
else:
    gaz_url = "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2024_Gazetteer/2024_Gaz_zcta_national.zip"
    try:
        import zipfile, io as _io
        r = requests.get(gaz_url, timeout=60)
        r.raise_for_status()
        z = zipfile.ZipFile(_io.BytesIO(r.content))
        txt_name = [n for n in z.namelist() if n.endswith(".txt")][0]
        z.extract(txt_name, RAW_DIR)
        extracted = os.path.join(RAW_DIR, txt_name)
        if extracted != gaz_path:
            os.rename(extracted, gaz_path)
        df_gaz = pd.read_csv(gaz_path, sep="\t", dtype=str)
        print(f"Downloaded Gazetteer: {len(df_gaz)} ZCTAs")
    except Exception as e:
        df_gaz = None
        print(f"Gazetteer download failed: {e}")

if df_gaz is not None:
    gaz_cols = df_gaz.columns.tolist()
    lat_col = next((c for c in gaz_cols if "lat" in c.lower()), None)
    lon_col = next((c for c in gaz_cols if "long" in c.lower() or "lon" in c.lower()), None)
    zcta_gaz_col = next((c for c in gaz_cols if "geoid" in c.lower() or "zcta" in c.lower()), gaz_cols[0])
    if lat_col and lon_col:
        df_gaz_slim = df_gaz[[zcta_gaz_col, lat_col, lon_col]].copy()
        df_gaz_slim.columns = ["zcta", "lat", "lon"]
        df_gaz_slim["lat"] = pd.to_numeric(df_gaz_slim["lat"], errors="coerce")
        df_gaz_slim["lon"] = pd.to_numeric(df_gaz_slim["lon"], errors="coerce")
        df_gaz_slim["zcta"] = df_gaz_slim["zcta"].astype(str).str.strip()
        print(f"Gazetteer centroids: {len(df_gaz_slim)} ZCTAs with lat/lon")

if len(df_zcta) > 0:
    df_zcta["zcta"] = df_zcta["zcta"].astype(str).str.strip()
    zcta_years = sorted(df_zcta["year"].unique())
    z_yr_min, z_yr_max = int(zcta_years[0]), int(zcta_years[-1])
    print(f"\nZCTA data: {len(df_zcta):,} rows | years: {z_yr_min}-{z_yr_max} | ZCTAs: {df_zcta['zcta'].nunique():,}")
else:
    print("No ZCTA data available")

In [ ]:
# ---- 11d (cont): ZCTA scatter-geo density maps with year slider ----

if len(df_zcta) > 0 and len(df_gaz_slim) > 0:
    ZCTA_VARS = [
        ("median_income",        "Median Household Income",  "$,.0f", "Viridis"),
        ("median_rent",          "Median Gross Rent",        "$,.0f", "Inferno"),
        ("median_home_value",    "Median Home Value",        "$,.0f", "Plasma"),
        ("vacancy_rate",         "Vacancy Rate",             ".1%",   "RdYlGn_r"),
        ("broadband_penetration","Broadband (%)",            ".1f",   "Blues"),
        ("in_migration_rate",    "In-Migration Rate (%)",    ".2f",   "Greens"),
        ("poverty_rate",         "Poverty Rate (%)",         ".1f",   "OrRd"),
        ("college_degree_pct",   "College Degree (%)",       ".1f",   "Purples"),
    ]

    for var_name, title, fmt, cscale in ZCTA_VARS:
        if var_name not in df_zcta.columns:
            continue

        df_latest_z = df_zcta[df_zcta["year"] == z_yr_max].merge(
            df_gaz_slim, on="zcta", how="inner"
        )
        vals = df_latest_z[var_name].dropna()
        if len(vals) == 0:
            continue
        p2, p98 = vals.quantile(0.02), vals.quantile(0.98)

        fig = go.Figure(go.Scattergeo(
            lat=df_latest_z["lat"], lon=df_latest_z["lon"],
            marker=dict(
                size=2.5, opacity=0.6,
                color=df_latest_z[var_name].clip(p2, p98),
                colorscale=cscale,
                colorbar=dict(title=title, thickness=12),
            ),
            hovertemplate=f"ZCTA: %{{text}}<br>{title}: %{{marker.color:{fmt}}}<extra></extra>",
            text=df_latest_z["zcta"],
        ))

        frames = []
        for yr in zcta_years:
            df_yr_z = df_zcta[df_zcta["year"] == yr].merge(df_gaz_slim, on="zcta", how="inner")
            frames.append(go.Frame(
                data=[go.Scattergeo(
                    lat=df_yr_z["lat"], lon=df_yr_z["lon"],
                    marker=dict(size=2.5, opacity=0.6,
                                color=df_yr_z[var_name].clip(p2, p98),
                                colorscale=cscale),
                    hovertemplate=f"ZCTA: %{{text}}<br>{title}: %{{marker.color:{fmt}}}<extra></extra>",
                    text=df_yr_z["zcta"],
                )],
                name=str(int(yr)),
            ))

        sliders = [dict(
            active=len(zcta_years) - 1,
            currentvalue={"prefix": "Year: ", "font": {"size": 14}},
            pad={"t": 50},
            steps=[dict(args=[[str(int(yr))], {"frame": {"duration": 500}, "mode": "immediate"}],
                         label=str(int(yr)), method="animate") for yr in zcta_years],
        )]

        fig.update_layout(
            title=dict(text=f"ZIP/ZCTA Level \u2014 {title} ({z_yr_min}-{z_yr_max})", font=dict(size=15)),
            geo=dict(scope="usa", showlakes=True, lakecolor="rgb(200,220,255)",
                     projection=dict(type="albers usa")),
            height=550, margin=dict(l=10, r=10, t=80, b=30),
            sliders=sliders,
            updatemenus=[dict(
                type="buttons", showactive=False, x=0.05, y=-0.02,
                buttons=[
                    dict(label="Play", method="animate",
                         args=[None, {"frame": {"duration": 800}, "fromcurrent": True}]),
                    dict(label="Pause", method="animate",
                         args=[[None], {"frame": {"duration": 0}, "mode": "immediate"}]),
                ],
            )],
        )
        fig.frames = frames
        fig.show()
        print(f"  ZCTA: {title}")

    print(f"\n--- ZCTA Level: {len(ZCTA_VARS)} scatter-geo density maps ({z_yr_min}-{z_yr_max}) ---")
else:
    print("ZCTA data or Gazetteer centroids not available for visualization")

### 11e. Tract-Level Visualizations (2015-2024)

Census tracts (~85,000 nationally) are too granular for a single national choropleth
to be readable. We use two approaches:
1. **National scatter-geo density** (one dot per tract centroid) for broad patterns
2. **State-filtered choropleth** (select a state to see tract-level detail within it)

Tract data is loaded from `census_tract_all_us_demographics_2015_2024.parquet` if available,
or fetched live (52 states x 10 years = 520 API calls -- ~30 min).

In [ ]:
# ---- 11e: TRACT-LEVEL VISUALIZATIONS ----

tract_path = os.path.join(DATA_DIR, "census_tract_all_us_demographics_2015_2024.parquet")
tiger_parquet = os.path.join(PROCESSED_DIR, "tiger_tracts.parquet")

if os.path.isfile(tract_path):
    print(f"Loading cached: {tract_path}")
    df_tr = pd.read_parquet(tract_path)
else:
    print("Tract data not cached. Fetching from Census ACS API...")
    print("  This will take ~30 min (52 states x 10 years = 520 API calls)")
    tr_frames, tr_errors = [], []
    for yr in YEARS:
        base_url = f"https://api.census.gov/data/{yr}/acs/{DATASET}"
        for st in ALL_STATE_FIPS:
            try:
                df_yr = fetch_census_three_batch(
                    base_url, {"for": "tract:*", "in": f"state:{st}"},
                    CENSUS_API_KEY, RENAME_MAP,
                    ["state", "county", "tract"],
                    include_c24050=(yr >= 2017),
                )
                df_yr["year"] = yr
                tr_frames.append(df_yr)
            except Exception as e:
                tr_errors.append(f"{yr}/{st}: {e}")
            time.sleep(0.15)
        n = sum(len(f) for f in tr_frames)
        print(f"  {yr}: {n:,} tracts total so far")
    df_tr = pd.concat(tr_frames, ignore_index=True) if tr_frames else pd.DataFrame()
    if len(df_tr) > 0:
        df_tr = compute_fmv_derived(df_tr)
        df_tr.to_parquet(tract_path, index=False, engine="pyarrow")
        print(f"Saved: {tract_path} ({len(df_tr):,} rows)")

# Build tract FIPS and load centroids from TIGER if available
if len(df_tr) > 0:
    df_tr["state"] = df_tr["state"].astype(str).str.zfill(2)
    df_tr["county"] = df_tr["county"].astype(str).str.zfill(3)
    df_tr["tract"] = df_tr["tract"].astype(str).str.zfill(6)
    df_tr["tract_fips"] = df_tr["state"] + df_tr["county"] + df_tr["tract"]
    tr_years = sorted(df_tr["year"].unique())
    tr_yr_min, tr_yr_max = int(tr_years[0]), int(tr_years[-1])
    print(f"Tract data: {len(df_tr):,} rows | years: {tr_yr_min}-{tr_yr_max} | tracts: {df_tr['tract_fips'].nunique():,}")

    # Try to get centroids from TIGER shapefiles
    tracts_gdf = None
    if os.path.isfile(tiger_parquet):
        try:
            tracts_gdf = gpd.read_parquet(tiger_parquet)
            if "INTPTLAT" in tracts_gdf.columns and "INTPTLON" in tracts_gdf.columns:
                tract_centroids = tracts_gdf[["GEOID", "INTPTLAT", "INTPTLON"]].copy()
                tract_centroids.columns = ["tract_fips", "lat", "lon"]
                tract_centroids["lat"] = pd.to_numeric(tract_centroids["lat"], errors="coerce")
                tract_centroids["lon"] = pd.to_numeric(tract_centroids["lon"], errors="coerce")
                print(f"TIGER centroids: {len(tract_centroids):,} tracts with lat/lon")
            else:
                tract_centroids = pd.DataFrame()
        except Exception as e:
            tract_centroids = pd.DataFrame()
            print(f"TIGER load error: {e}")
    else:
        tract_centroids = pd.DataFrame()
        print("TIGER shapefiles not cached -- tract scatter maps will be skipped")
else:
    tr_years = []
    tract_centroids = pd.DataFrame()
    print("No tract data available")

In [ ]:
# ---- 11e (cont): National tract-level scatter-geo density maps ----

if len(df_tr) > 0 and len(tract_centroids) > 0:
    TRACT_VARS = [
        ("median_income",        "Median Household Income",  "$,.0f", "Viridis"),
        ("median_rent",          "Median Gross Rent",        "$,.0f", "Inferno"),
        ("median_home_value",    "Median Home Value",        "$,.0f", "Plasma"),
        ("vacancy_rate",         "Vacancy Rate",             ".1%",   "RdYlGn_r"),
        ("poverty_rate",         "Poverty Rate (%)",         ".1f",   "OrRd"),
        ("broadband_penetration","Broadband (%)",            ".1f",   "Blues"),
    ]

    for var_name, title, fmt, cscale in TRACT_VARS:
        if var_name not in df_tr.columns:
            continue

        df_latest_tr = df_tr[df_tr["year"] == tr_yr_max].merge(
            tract_centroids, on="tract_fips", how="inner"
        )
        # Subsample for rendering performance (~30k tracts max per frame)
        if len(df_latest_tr) > 30000:
            df_latest_tr = df_latest_tr.sample(n=30000, random_state=42)

        vals = df_latest_tr[var_name].dropna()
        if len(vals) == 0:
            continue
        p2, p98 = vals.quantile(0.02), vals.quantile(0.98)

        fig = go.Figure(go.Scattergeo(
            lat=df_latest_tr["lat"], lon=df_latest_tr["lon"],
            marker=dict(size=1.5, opacity=0.5,
                        color=df_latest_tr[var_name].clip(p2, p98),
                        colorscale=cscale,
                        colorbar=dict(title=title, thickness=12)),
            hovertemplate=f"Tract: %{{text}}<br>{title}: %{{marker.color:{fmt}}}<extra></extra>",
            text=df_latest_tr["tract_fips"],
        ))

        frames = []
        for yr in tr_years:
            df_yr_tr = df_tr[df_tr["year"] == yr].merge(
                tract_centroids, on="tract_fips", how="inner"
            )
            if len(df_yr_tr) > 30000:
                df_yr_tr = df_yr_tr.sample(n=30000, random_state=42)
            frames.append(go.Frame(
                data=[go.Scattergeo(
                    lat=df_yr_tr["lat"], lon=df_yr_tr["lon"],
                    marker=dict(size=1.5, opacity=0.5,
                                color=df_yr_tr[var_name].clip(p2, p98),
                                colorscale=cscale),
                    hovertemplate=f"Tract: %{{text}}<br>{title}: %{{marker.color:{fmt}}}<extra></extra>",
                    text=df_yr_tr["tract_fips"],
                )],
                name=str(int(yr)),
            ))

        sliders = [dict(
            active=len(tr_years) - 1,
            currentvalue={"prefix": "Year: ", "font": {"size": 14}},
            pad={"t": 50},
            steps=[dict(args=[[str(int(yr))], {"frame": {"duration": 500}, "mode": "immediate"}],
                         label=str(int(yr)), method="animate") for yr in tr_years],
        )]

        fig.update_layout(
            title=dict(text=f"Tract Level \u2014 {title} ({tr_yr_min}-{tr_yr_max})", font=dict(size=15)),
            geo=dict(scope="usa", showlakes=True, lakecolor="rgb(200,220,255)",
                     projection=dict(type="albers usa")),
            height=550, margin=dict(l=10, r=10, t=80, b=30),
            sliders=sliders,
            updatemenus=[dict(
                type="buttons", showactive=False, x=0.05, y=-0.02,
                buttons=[
                    dict(label="Play", method="animate",
                         args=[None, {"frame": {"duration": 800}, "fromcurrent": True}]),
                    dict(label="Pause", method="animate",
                         args=[[None], {"frame": {"duration": 0}, "mode": "immediate"}]),
                ],
            )],
        )
        fig.frames = frames
        fig.show()
        print(f"  Tract: {title}")

    print(f"\n--- Tract Level: {len(TRACT_VARS)} national scatter-geo maps ({tr_yr_min}-{tr_yr_max}) ---")
elif len(df_tr) > 0:
    print("Tract centroids not available -- showing distribution summaries instead")
    key_attrs = ["median_income", "median_home_value", "median_rent",
                 "poverty_rate", "vacancy_rate", "broadband_penetration"]
    avail = [a for a in key_attrs if a in df_tr.columns]
    df_tr_ann = df_tr.groupby("year")[avail].median().reset_index()
    n_cols = 3
    n_rows = (len(avail) + n_cols - 1) // n_cols
    fig = make_subplots(rows=n_rows, cols=n_cols,
                        subplot_titles=[a.replace("_", " ").title() for a in avail],
                        shared_xaxes=True, vertical_spacing=0.14)
    colors = px.colors.qualitative.D3
    for idx, attr in enumerate(avail):
        r, c = divmod(idx, n_cols)
        fig.add_trace(
            go.Scatter(x=df_tr_ann["year"], y=df_tr_ann[attr],
                       mode="lines+markers", name=attr.replace("_", " ").title(),
                       line=dict(color=colors[idx % len(colors)], width=2),
                       showlegend=False),
            row=r + 1, col=c + 1)
    fig.update_layout(
        title=f"Tract Level \u2014 National Median Trends ({tr_yr_min}-{tr_yr_max})",
        height=400 * n_rows, margin=dict(l=50, r=30, t=80, b=40))
    fig.update_xaxes(dtick=2)
    fig.show()
else:
    print("No tract data available for visualization")

### 11f. Macro Economic Indicators -- FRED National & State Trends (2005-Present)

FRED macro indicators provide the national economic context that affects cell tower
lease FMV across all geographies. State-level FRED indicators (unemployment, GDP,
building permits) show regional economic divergence.

In [ ]:
# ---- 11f: FRED MACRO INDICATORS (2005-Present) ----

df_fred = pd.read_parquet(os.path.join(PROCESSED_DIR, "fred_national_macro.parquet"))
df_fred["date"] = pd.to_datetime(df_fred["date"])

FRED_PANELS = [
    {
        "title": "Inflation & Home Prices (2005-Present)",
        "series": [
            ("CPIAUCSL", "CPI (All Urban Consumers)", "#1f77b4"),
            ("CSUSHPINSA", "Case-Shiller Home Price Index", "#ff7f0e"),
        ],
    },
    {
        "title": "Interest Rates & Mortgage (2005-Present)",
        "series": [
            ("DGS10", "10-Year Treasury", "#2ca02c"),
            ("FEDFUNDS", "Fed Funds Rate", "#d62728"),
            ("MORTGAGE30US", "30-Year Mortgage", "#9467bd"),
        ],
    },
    {
        "title": "Employment (2005-Present)",
        "series": [
            ("UNRATE", "Unemployment Rate (%)", "#e377c2"),
            ("PAYEMS", "Nonfarm Payrolls (000s)", "#7f7f7f"),
        ],
    },
    {
        "title": "Housing Supply & Sentiment (2005-Present)",
        "series": [
            ("HOUST", "Housing Starts (000s)", "#bcbd22"),
            ("PERMIT", "Building Permits", "#17becf"),
            ("UMCSENT", "Consumer Sentiment", "#8c564b"),
        ],
    },
]

for panel in FRED_PANELS:
    avail = [(sid, lbl, clr) for sid, lbl, clr in panel["series"] if sid in df_fred.columns]
    if not avail:
        continue
    n_rows = len(avail)
    fig = make_subplots(rows=n_rows, cols=1,
                        subplot_titles=[lbl for _, lbl, _ in avail],
                        shared_xaxes=True, vertical_spacing=0.08)
    for idx, (sid, lbl, clr) in enumerate(avail):
        vals = df_fred.dropna(subset=[sid])
        fig.add_trace(
            go.Scatter(x=vals["date"], y=vals[sid], name=lbl,
                       line=dict(color=clr, width=1.5), showlegend=False),
            row=idx + 1, col=1)
    fig.update_layout(
        title=dict(text=panel["title"], font=dict(size=15)),
        height=200 * n_rows + 80, margin=dict(l=60, r=30, t=80, b=40))
    fig.update_xaxes(dtick="M24")
    fig.show()

# State-level FRED with choropleth (latest year annual averages)
df_st_macro = pd.read_parquet(os.path.join(PROCESSED_DIR, "fred_state_macro.parquet"))
df_st_macro["date"] = pd.to_datetime(df_st_macro["date"])
df_st_macro["year"] = df_st_macro["date"].dt.year

for col, title, cscale in [
    ("unemployment_rate", "State Unemployment Rate (%)", "YlOrRd"),
    ("building_permits",  "State Building Permits (Annual Total)", "Blues"),
]:
    if col not in df_st_macro.columns:
        continue

    if col == "building_permits":
        st_annual = df_st_macro.groupby(["state_abbr", "year"])[col].sum().reset_index()
    else:
        st_annual = df_st_macro.groupby(["state_abbr", "year"])[col].mean().reset_index()

    st_years = sorted(st_annual["year"].unique())
    # Only show years >= 2005
    st_years = [y for y in st_years if y >= 2005]
    if not st_years:
        continue
    st_latest = st_annual[st_annual["year"] == st_years[-1]]

    fig = go.Figure(go.Choropleth(
        locations=st_latest["state_abbr"], z=st_latest[col],
        locationmode="USA-states", colorscale=cscale,
        colorbar=dict(title=title.split("(")[0].strip(), thickness=15),
        hovertemplate=f"<b>%{{location}}</b><br>{title}: %{{z:.1f}}<extra></extra>",
    ))

    frames = [
        go.Frame(
            data=[go.Choropleth(
                locations=st_annual[st_annual["year"] == yr]["state_abbr"],
                z=st_annual[st_annual["year"] == yr][col],
                locationmode="USA-states", colorscale=cscale,
                hovertemplate=f"<b>%{{location}}</b><br>{title}: %{{z:.1f}}<extra></extra>",
            )],
            name=str(yr),
        )
        for yr in st_years
    ]

    sliders = [dict(
        active=len(st_years) - 1,
        currentvalue={"prefix": "Year: ", "font": {"size": 14}},
        pad={"t": 50},
        steps=[dict(args=[[str(yr)], {"frame": {"duration": 300}, "mode": "immediate"}],
                     label=str(yr), method="animate") for yr in st_years],
    )]

    fig.update_layout(
        title=dict(text=f"{title} \u2014 State Choropleth (2005-{st_years[-1]})", font=dict(size=15)),
        geo=dict(scope="usa", showlakes=True, projection=dict(type="albers usa")),
        height=500, margin=dict(l=10, r=10, t=80, b=30),
        sliders=sliders,
        updatemenus=[dict(
            type="buttons", showactive=False, x=0.05, y=-0.02,
            buttons=[
                dict(label="Play", method="animate",
                     args=[None, {"frame": {"duration": 500}, "fromcurrent": True}]),
                dict(label="Pause", method="animate",
                     args=[[None], {"frame": {"duration": 0}, "mode": "immediate"}]),
            ],
        )],
    )
    fig.frames = frames
    fig.show()
    print(f"  FRED State: {title}")

print("\n--- FRED Macro: national trend panels + state choropleths (2005-present) ---")

---
## 12. Source-Mapped Additional Indicators for FMV Prediction

Definitive mapping of 25 additional FMV indicator variables to their **actual data sources**
(Census ACS, FRED API, BLS, OpenCelliD, FCC). Each variable is evaluated for:
- Whether it can be pulled from an existing open-source API
- How FCC and OpenCelliD data fields specifically enable new variables
- How each variable helps predict FMV by property type (residential, commercial, rooftop, empty plot)

In [ ]:
# ---- 12: Source-Mapped Additional Indicators ----
# Each variable mapped to its ACTUAL data source with verified API/download access.

additional_indicators = pd.DataFrame([
    # ======================================================================
    # TIER 1 -- AVAILABLE NOW VIA EXISTING PIPELINES (Census, FRED, BLS, OpenCelliD, FCC)
    # ======================================================================
    {
        "category": "FRED (addable now)",
        "variable": "FHFA Purchase-Only HPI (Quarterly)",
        "source": "FRED",
        "series_or_table": "PONHPIM226S (national), [ST]STHPI (state)",
        "why_fmv": "More timely than annual HPI; captures price momentum affecting lease negotiations",
        "property_impact": "ALL: Higher HPI = higher opportunity cost = higher rents across all property types",
        "geographic_level": "National / State / MSA",
        "access_method": "fredapi Python package (already in pipeline)",
        "actionable": "YES",
    },
    {
        "category": "FRED (addable now)",
        "variable": "Commercial Real Estate Price Index",
        "source": "FRED",
        "series_or_table": "BOGZ1FL075035503Q (CRE index), COMREPUSQ159N (CRE % chg)",
        "why_fmv": "CRE pricing directly affects commercial rooftop/building lease valuations",
        "property_impact": "COMMERCIAL: Direct driver. ROOFTOP: Strong correlation with building values",
        "geographic_level": "National",
        "access_method": "fredapi Python package",
        "actionable": "YES",
    },
    {
        "category": "FRED (addable now)",
        "variable": "Telecom Construction Spending",
        "source": "FRED",
        "series_or_table": "TLCMUCONS (monthly), C275RC1A027NBEA (annual)",
        "why_fmv": "Proxy for wireless CAPEX; higher spending = more tower demand = higher FMV",
        "property_impact": "ALL: Leading indicator of new lease demand",
        "geographic_level": "National",
        "access_method": "fredapi Python package",
        "actionable": "YES",
    },
    {
        "category": "FRED (addable now)",
        "variable": "CRE Loan Delinquency Rate",
        "source": "FRED",
        "series_or_table": "DRCRELEXFACBS",
        "why_fmv": "CRE market stress indicator; distressed properties may accept lower tower lease rents",
        "property_impact": "COMMERCIAL: Distressed owners more willing to lease. ROOFTOP: Bargaining leverage",
        "geographic_level": "National",
        "access_method": "fredapi Python package",
        "actionable": "YES",
    },
    {
        "category": "FRED (addable now)",
        "variable": "Telecom Employment",
        "source": "FRED",
        "series_or_table": "CES5051700001 (All Employees, Telecom)",
        "why_fmv": "Industry health proxy; growing workforce = expanding networks = lease demand",
        "property_impact": "ALL: Macro demand signal for tower leasing activity",
        "geographic_level": "National",
        "access_method": "fredapi Python package",
        "actionable": "YES",
    },
    {
        "category": "FRED (addable now)",
        "variable": "Multi-Family CRE Price Index",
        "source": "FRED",
        "series_or_table": "BOGZ1FL075035403Q",
        "why_fmv": "Multi-family building values directly affect rooftop lease negotiating leverage",
        "property_impact": "ROOFTOP: Primary driver for apartment building owners. RESIDENTIAL: Strong correlation",
        "geographic_level": "National",
        "access_method": "fredapi Python package",
        "actionable": "YES",
    },
    # ======================================================================
    # TIER 2 -- AVAILABLE VIA OpenCelliD (already downloaded in Section 4d)
    # ======================================================================
    {
        "category": "OpenCelliD (computable now)",
        "variable": "Tower Density per Area",
        "source": "OpenCelliD",
        "series_or_table": "cell_towers.csv.gz: group by tract/county, count cells",
        "why_fmv": "Low density = scarcity premium (20-50% higher rents); high density = competition",
        "property_impact": "EMPTY PLOT: Scarcity is the #1 driver for ground lease FMV. ROOFTOP: Less impacted",
        "geographic_level": "Tract / County (computed)",
        "access_method": "Already downloaded; spatial join with TIGER tracts",
        "actionable": "YES",
    },
    {
        "category": "OpenCelliD (computable now)",
        "variable": "Carrier Competition Index",
        "source": "OpenCelliD",
        "series_or_table": "cell_towers.csv.gz: count distinct MNC per area",
        "why_fmv": "More carriers competing in an area = more potential tenants = higher FMV",
        "property_impact": "ALL: Multi-carrier areas have co-location potential increasing value 2-4x",
        "geographic_level": "Tract / County (computed)",
        "access_method": "Filter mcc IN (310-316), groupby area, nunique(net)",
        "actionable": "YES",
    },
    {
        "category": "OpenCelliD (computable now)",
        "variable": "4G/5G Technology Readiness Score",
        "source": "OpenCelliD",
        "series_or_table": "cell_towers.csv.gz: radio field (LTE, NR counts)",
        "why_fmv": "Areas with 5G NR deployment indicate carrier investment; higher FMV",
        "property_impact": "ROOFTOP: 5G small cells prefer rooftops. COMMERCIAL: DAS installations in malls",
        "geographic_level": "Tract / County (computed)",
        "access_method": "(LTE_count + NR_count) / total_count per area",
        "actionable": "YES",
    },
    {
        "category": "OpenCelliD (computable now)",
        "variable": "Distance to Nearest Competing Tower",
        "source": "OpenCelliD",
        "series_or_table": "cell_towers.csv.gz: BallTree nearest-neighbor",
        "why_fmv": "Isolation premium: towers >2km from alternatives command 20-50% higher rents",
        "property_impact": "EMPTY PLOT: Primary FMV driver. RURAL sites with no alternatives = maximum leverage",
        "geographic_level": "Site-level (computed)",
        "access_method": "sklearn.neighbors.BallTree on lat/lon coordinates",
        "actionable": "YES",
    },
    {
        "category": "OpenCelliD (computable now)",
        "variable": "Co-location Density (cells per physical location)",
        "source": "OpenCelliD",
        "series_or_table": "cell_towers.csv.gz: group by rounded lat/lon (4 dec)",
        "why_fmv": "Sites already hosting multiple carriers prove co-location viability",
        "property_impact": "ALL: Proven co-location sites are valued at 2-4x single-tenant sites",
        "geographic_level": "Site-level (computed)",
        "access_method": "Group by lat.round(4)/lon.round(4), count distinct MNC",
        "actionable": "YES",
    },
    {
        "category": "OpenCelliD (computable now)",
        "variable": "Estimated Cell Range / Coverage Radius",
        "source": "OpenCelliD",
        "series_or_table": "cell_towers.csv.gz: range field (meters)",
        "why_fmv": "Smaller range cells (small cells/DAS) indicate urban densification demand",
        "property_impact": "ROOFTOP: Small cells (<500m range) prefer rooftops in dense urban areas",
        "geographic_level": "Site-level",
        "access_method": "Direct field; classify: <500m=small cell, >1000m=macro",
        "actionable": "YES",
    },
    # ======================================================================
    # TIER 3 -- FCC ASR DATA (bulk download, new pipeline step)
    # ======================================================================
    {
        "category": "FCC ASR (new pipeline)",
        "variable": "Registered Tower Density per County",
        "source": "FCC ASR",
        "series_or_table": "r_tower.zip -> RA table: status_code='C', group by county_code",
        "why_fmv": "Official tower count more accurate than OpenCelliD (no crowd-source bias)",
        "property_impact": "EMPTY PLOT: Directly determines supply/scarcity pricing",
        "geographic_level": "County / ZIP (via county_code, zip_code)",
        "access_method": "Bulk download: data.fcc.gov/download/pub/uls/complete/r_tower.zip (weekly, pipe-delimited)",
        "actionable": "YES",
    },
    {
        "category": "FCC ASR (new pipeline)",
        "variable": "Tower Structure Type Distribution",
        "source": "FCC ASR",
        "series_or_table": "RA.structure_type: TOWER, BANT, BTWR, POLE, LTWR, UTIL, etc.",
        "why_fmv": "Building-mounted (BANT/BTWR) vs ground (TOWER/LTWR) mix reveals local siting patterns",
        "property_impact": "ROOFTOP: High BANT/BTWR % = urban; carriers prefer rooftops. EMPTY PLOT: High TOWER % = rural ground leases",
        "geographic_level": "County / ZIP",
        "access_method": "Parse RA table, group by county_code + structure_type",
        "actionable": "YES",
    },
    {
        "category": "FCC ASR (new pipeline)",
        "variable": "Tower Height (AGL meters)",
        "source": "FCC ASR",
        "series_or_table": "RA.height_of_structure, RA.overall_height_above_ground",
        "why_fmv": "Taller towers serve wider areas; height is a direct value multiplier for ground leases",
        "property_impact": "EMPTY PLOT: Taller towers = higher rent. ROOFTOP: Building height from RA.ground_elevation as proxy",
        "geographic_level": "Site-level / County median",
        "access_method": "Parse RA table; median height_of_structure per county",
        "actionable": "YES",
    },
    {
        "category": "FCC ASR (new pipeline)",
        "variable": "Co-location via ULS Cross-Reference",
        "source": "FCC ASR + ULS",
        "series_or_table": "ULS LO.tower_registration_number = ASR RA.registration_number",
        "why_fmv": "Exact co-location count from official license data (not estimated like OpenCelliD)",
        "property_impact": "ALL: Multi-tenant towers earn 2-4x; proven co-location is the strongest FMV driver",
        "geographic_level": "Site-level",
        "access_method": "Download r_tower.zip + l_cell.zip; join on registration_number/tower_registration_number",
        "actionable": "YES (moderate effort)",
    },
    # ======================================================================
    # TIER 4 -- FCC BDC (Broadband Data Collection)
    # ======================================================================
    {
        "category": "FCC BDC (new pipeline)",
        "variable": "Broadband Availability by Census Block",
        "source": "FCC BDC",
        "series_or_table": "Fixed broadband CSV: technology_code, max_download/upload_speed, block_geoid",
        "why_fmv": "Areas with poor fixed broadband rely more on wireless; higher tower lease demand",
        "property_impact": "ALL: Low fixed broadband = higher wireless dependency = higher FMV for all property types",
        "geographic_level": "Census Block / Tract",
        "access_method": "broadbandmap.fcc.gov/data-download (bulk CSV by state, semi-annual)",
        "actionable": "YES",
    },
    {
        "category": "FCC BDC (new pipeline)",
        "variable": "Fiber Availability (Technology Code 50)",
        "source": "FCC BDC",
        "series_or_table": "technology_code=50 (Fiber to Premises) per block_geoid",
        "why_fmv": "Fiber presence = potential backhaul for 5G; carriers pay 15-25% premium for fiber-lit sites",
        "property_impact": "ALL: Fiber-proximate sites support 5G and higher-value leases",
        "geographic_level": "Census Block / Tract",
        "access_method": "Filter technology_code=50, aggregate to tract level",
        "actionable": "YES",
    },
    # ======================================================================
    # TIER 5 -- CENSUS ACS (already in pipeline, new derived variables)
    # ======================================================================
    {
        "category": "Census ACS (computable now)",
        "variable": "Population Density per Sq Km",
        "source": "Census ACS + TIGER",
        "series_or_table": "B01003_001E (population) / TIGER ALAND (land area sq meters)",
        "why_fmv": "Direct proxy for wireless subscriber density; #1 predictor of tower lease demand",
        "property_impact": "ALL: Dense areas = higher FMV. ROOFTOP premium in urban; EMPTY PLOT premium in suburban",
        "geographic_level": "Tract / County / Block Group",
        "access_method": "Already have both datasets; compute population / (ALAND/1e6)",
        "actionable": "YES",
    },
    {
        "category": "Census ACS (computable now)",
        "variable": "Commuter Worker Count (daytime pop proxy)",
        "source": "Census ACS",
        "series_or_table": "B08301_001E (total workers commuting)",
        "why_fmv": "High commuter count = large daytime population = more wireless users during business hours",
        "property_impact": "COMMERCIAL: Business district towers serve commuter phones. ROOFTOP: Office building premium",
        "geographic_level": "Tract / County",
        "access_method": "Already fetched in pipeline (B08301_001E = total_commuters)",
        "actionable": "YES (already in data)",
    },
    {
        "category": "Census ACS (computable now)",
        "variable": "Seasonal Vacancy Rate (tourist proxy)",
        "source": "Census ACS",
        "series_or_table": "B25004_006E (vacant seasonal) / B25002_001E (total units)",
        "why_fmv": "High seasonal vacancy = tourist/resort area with seasonal demand spikes",
        "property_impact": "ALL: Tourist areas have peak-season capacity needs driving tower demand",
        "geographic_level": "Tract / County / ZCTA",
        "access_method": "Already fetched (vacant_seasonal / total_housing_units)",
        "actionable": "YES (already in data)",
    },
    {
        "category": "Census ACS (computable now)",
        "variable": "Structure Type Mix (multi-family %)",
        "source": "Census ACS",
        "series_or_table": "B25024_002E-011E (units in structure types)",
        "why_fmv": "High multi-family % indicates rooftop lease opportunities on apartment buildings",
        "property_impact": "ROOFTOP: Direct indicator. RESIDENTIAL: Apartment owners negotiate differently than homeowners",
        "geographic_level": "Tract / County",
        "access_method": "Already fetched (multifamily_pct, single_family_pct)",
        "actionable": "YES (already in data)",
    },
    # ======================================================================
    # TIER 6 -- NOT AVAILABLE VIA OPEN APIs (requires manual/commercial sources)
    # ======================================================================
    {
        "category": "Not available (open API)",
        "variable": "Tower REIT Acquisition Multiples",
        "source": "SEC EDGAR / Industry reports",
        "series_or_table": "10-K filings from AMT, CCI, SBAC",
        "why_fmv": "Market multiple directly sets baseline FMV expectations",
        "property_impact": "ALL: Sets overall market pricing level",
        "geographic_level": "National",
        "access_method": "Manual extraction from SEC filings; no open API",
        "actionable": "NO (manual)",
    },
    {
        "category": "Not available (open API)",
        "variable": "Wireless Data Traffic Growth",
        "source": "CTIA / Ericsson",
        "series_or_table": "CTIA Annual Wireless Survey",
        "why_fmv": "Data growth drives network densification",
        "property_impact": "ALL: Demand-side macro factor",
        "geographic_level": "National",
        "access_method": "CTIA annual reports (no open API)",
        "actionable": "NO (manual)",
    },
    {
        "category": "Not available (open API)",
        "variable": "Building Height / Stories",
        "source": "MS Building Footprints / County assessor",
        "series_or_table": "Various county assessor schemas",
        "why_fmv": "Taller buildings = better signal propagation = premium rooftop rents",
        "property_impact": "ROOFTOP: Primary value driver for rooftop leases",
        "geographic_level": "Parcel-level",
        "access_method": "github.com/microsoft/USBuildingFootprints (free but no API); county varies",
        "actionable": "PARTIAL (MS Footprints downloadable)",
    },
    {
        "category": "Not available (open API)",
        "variable": "Parcel Size / Land Area",
        "source": "County assessor / Regrid",
        "series_or_table": "County-specific parcel databases",
        "why_fmv": "Larger parcels accommodate compound ground leases with multiple carriers",
        "property_impact": "EMPTY PLOT: Direct driver; larger lot = more equipment space = higher rent",
        "geographic_level": "Parcel-level",
        "access_method": "regrid.com (paid API); county GIS portals (free, inconsistent)",
        "actionable": "NO (fragmented)",
    },
])

print(f"Source-Mapped FMV Indicators: {len(additional_indicators)} variables across "
      f"{additional_indicators['category'].nunique()} source tiers\n")

for cat, grp in additional_indicators.groupby("category", sort=False):
    actionable_count = (grp["actionable"].str.startswith("YES")).sum()
    print(f"\n{'='*90}")
    print(f"  {cat} ({len(grp)} variables, {actionable_count} actionable)")
    print(f"{'='*90}")
    for _, row in grp.iterrows():
        flag = "[OK]" if row["actionable"].startswith("YES") else "[--]"
        print(f"\n  {flag} {row['variable']}")
        print(f"       Source:   {row['series_or_table']}")
        print(f"       FMV:     {row['why_fmv']}")
        print(f"       Impact:  {row['property_impact']}")
        print(f"       Level:   {row['geographic_level']}")
        print(f"       Method:  {row['access_method']}")

actionable = additional_indicators[additional_indicators["actionable"].str.startswith("YES")]
print(f"\n\n{'='*90}")
print(f"SUMMARY: {len(actionable)}/{len(additional_indicators)} variables are actionable via open APIs")
print(f"  FRED:       {(actionable['source']=='FRED').sum()} new series to add")
print(f"  OpenCelliD: {(actionable['source']=='OpenCelliD').sum()} derived variables (data already downloaded)")
print(f"  FCC ASR:    {(actionable['source']=='FCC ASR').sum()} variables (new bulk download needed)")
print(f"  FCC BDC:    {(actionable['source']=='FCC BDC').sum()} variables (new bulk download needed)")
print(f"  Census ACS: {(actionable['source'].str.contains('Census')).sum()} variables (already in pipeline)")
print(f"{'='*90}")

In [ ]:
# ---- 12b: FCC ASR + OpenCelliD Data Field Analysis & FMV Linkage ----

print("=" * 90)
print("  FCC ASR DATABASE -- KEY FIELDS FOR FMV PREDICTION")
print("=" * 90)

fcc_fields = pd.DataFrame([
    ("RA.registration_number",      "7-digit ASR ID",                "Join key for co-location via ULS"),
    ("RA.status_code",              "C=Constructed, T=Terminated",   "Filter to active towers only"),
    ("RA.structure_type",           "TOWER/BANT/BTWR/POLE/LTWR...", "Identifies rooftop (BANT/BTWR) vs ground (TOWER)"),
    ("RA.height_of_structure",      "Height AGL in meters",          "Taller = wider coverage = higher FMV"),
    ("RA.overall_height_amsl",      "Height above sea level",        "Signal propagation advantage"),
    ("RA.ground_elevation",         "Ground elevation AMSL meters",  "Topographic advantage for signal"),
    ("RA.county_code",              "5-digit FIPS",                  "Join to census data at county level"),
    ("RA.zip_code",                 "ZIP code",                      "Join to ZCTA-level census data"),
    ("RA.structure_city/state",     "City, state",                   "Location identification"),
    ("CO.latitude/longitude",       "NAD83 coordinates (DMS)",       "Spatial analysis: density, nearest-neighbor"),
    ("EN.entity_name",              "Tower owner company",           "Identifies tower company (AMT, CCI, SBA)"),
    ("EN.frn",                      "FCC Registration Number",       "Cross-reference with ULS and BDC"),
    ("ULS LO.tower_registration_number", "ASR cross-reference",     "COUNT of ULS records per ASR = co-location count"),
], columns=["field", "content", "fmv_relevance"])

for _, row in fcc_fields.iterrows():
    print(f"  {row['field']:42s} | {row['content']:35s} | {row['fmv_relevance']}")

print(f"\n  Download: https://data.fcc.gov/download/pub/uls/complete/r_tower.zip (weekly, ~37MB)")
print(f"  Format:   Pipe-delimited (|) text files inside ZIP")
print(f"  Tables:   RA (registration), CO (coordinates), EN (entity), + 5 others")

print(f"\n\n{'='*90}")
print("  OpenCelliD DATABASE -- KEY FIELDS FOR FMV PREDICTION")
print("=" * 90)

oci_fields = pd.DataFrame([
    ("radio",          "GSM/UMTS/LTE/CDMA/NR", "Technology mix: NR=5G indicates carrier investment"),
    ("mcc",            "Mobile Country Code",   "US: 310-316; filter to US towers"),
    ("net (MNC)",      "Mobile Network Code",   "Carrier ID: 410=AT&T, 480=Verizon, 260=T-Mobile"),
    ("lat, lon",       "WGS84 coordinates",     "Spatial: density, nearest-neighbor, coverage gaps"),
    ("range",          "Coverage radius (m)",   "Small cell (<500m) vs macro (>1km) classification"),
    ("samples",        "Measurement count",     "Data quality indicator; higher = more reliable"),
    ("changeable",     "0=GPS exact, 1=estimated", "Use changeable=0 for precise co-location analysis"),
    ("averageSignal",  "Signal strength (dBm)",  "Network quality proxy; weaker = capacity need"),
    ("created/updated","Unix timestamps",        "Network age/freshness; recent = active investment"),
], columns=["field", "content", "fmv_relevance"])

for _, row in oci_fields.iterrows():
    print(f"  {row['field']:20s} | {row['content']:28s} | {row['fmv_relevance']}")

print(f"\n  Download: opencellid.org bulk CSV (2/day, ~900MB compressed)")
print(f"  API:      1,000 requests/day, max 50 cells per area query")
print(f"  US cells: ~7.96M total (5.3M LTE, 1.6M UMTS, 137K NR)")
print(f"  Key:      Bulk download is the ONLY viable approach for US-scale analysis")

# ---- Property-Type FMV Impact Matrix ----
print(f"\n\n{'='*90}")
print("  HOW EACH DATA SOURCE PREDICTS FMV BY PROPERTY TYPE")
print("=" * 90)

impact_matrix = pd.DataFrame([
    ("Population density",        "Census ACS",    "HIGH",   "HIGH",     "HIGH",    "MEDIUM"),
    ("Median income",             "Census ACS",    "MEDIUM", "MEDIUM",   "MEDIUM",  "LOW"),
    ("Vacancy rate",              "Census ACS",    "HIGH",   "MEDIUM",   "HIGH",    "HIGH"),
    ("Broadband penetration",     "Census ACS",    "HIGH",   "HIGH",     "HIGH",    "HIGH"),
    ("Tower density (scarcity)",  "OpenCelliD/FCC","HIGH",   "MEDIUM",   "HIGH",    "HIGHEST"),
    ("Nearest tower distance",    "OpenCelliD/FCC","MEDIUM", "MEDIUM",   "HIGH",    "HIGHEST"),
    ("Co-location count",         "FCC ASR+ULS",   "HIGH",   "HIGHEST",  "HIGH",    "HIGH"),
    ("Carrier competition",       "OpenCelliD",    "HIGH",   "HIGH",     "HIGH",    "HIGH"),
    ("5G NR presence",            "OpenCelliD",    "HIGH",   "HIGHEST",  "HIGH",    "LOW"),
    ("Structure type (BANT/TOWER)","FCC ASR",      "LOW",    "LOW",      "HIGH",    "LOW"),
    ("Tower height",              "FCC ASR",       "LOW",    "LOW",      "MEDIUM",  "HIGH"),
    ("Fiber availability",        "FCC BDC",       "HIGH",   "HIGH",     "HIGH",    "HIGH"),
    ("CRE price index",           "FRED",          "LOW",    "HIGH",     "HIGH",    "MEDIUM"),
    ("Mortgage/interest rates",   "FRED",          "MEDIUM", "MEDIUM",   "MEDIUM",  "LOW"),
    ("FHFA HPI trend",            "FRED",          "HIGH",   "HIGH",     "HIGH",    "MEDIUM"),
    ("Telecom construction spend","FRED",          "MEDIUM", "MEDIUM",   "MEDIUM",  "MEDIUM"),
], columns=["variable", "source", "residential", "commercial", "rooftop", "empty_plot"])

print(f"\n  {'Variable':<30s} {'Source':<15s} {'Resid.':<10s} {'Comm.':<10s} {'Rooftop':<10s} {'Empty Plot':<10s}")
print(f"  {'-'*85}")
for _, row in impact_matrix.iterrows():
    print(f"  {row['variable']:<30s} {row['source']:<15s} {row['residential']:<10s} "
          f"{row['commercial']:<10s} {row['rooftop']:<10s} {row['empty_plot']:<10s}")

---
## 12c. Implementation Roadmap

### Immediate Actions (no new data downloads needed)

| # | Action | Source | Effort |
|---|--------|--------|--------|
| 1 | Add 6 new FRED series (`PONHPIM226S`, `BOGZ1FL075035503Q`, `TLCMUCONS`, `DRCRELEXFACBS`, `CES5051700001`, `BOGZ1FL075035403Q`) | FRED API | 30 min |
| 2 | Compute `population_density_sqkm` = population / (ALAND/1e6) at tract level | Census ACS + TIGER | 10 min |
| 3 | Compute `seasonal_vacancy_rate` = vacant_seasonal / total_housing_units | Census ACS | 5 min |
| 4 | From OpenCelliD (already downloaded): compute tower_density, carrier_competition, tech_readiness, nearest_tower_distance, colocation_density, cell_range_category per tract | OpenCelliD | 1 hr |

### New Data Pipelines Needed

| # | Source | Download URL | Size | New Variables |
|---|--------|-------------|------|--------------|
| 5 | FCC ASR | `data.fcc.gov/download/pub/uls/complete/r_tower.zip` | ~37 MB | Tower density, structure type, height, owner |
| 6 | FCC ULS (Cellular) | `data.fcc.gov/download/pub/uls/complete/l_cell.zip` | ~16 MB | Co-location count (join ASR registration_number) |
| 7 | FCC BDC | `broadbandmap.fcc.gov/data-download` (by state) | ~2 GB | Broadband availability, fiber presence per block |

### Cross-Database Join Strategy
```
OpenCelliD (lat/lon) ----spatial join----> TIGER Tracts (GEOID)
FCC ASR (county_code, zip_code) --------> Census county/ZCTA
FCC ASR (registration_number) ---------=> FCC ULS (tower_registration_number) = co-location
FCC BDC (block_geoid[:11]) -------------> Census Tract
FRED (year) ----------------------------> Census ACS (year)
```

### FMV Prediction: What Matters Most by Property Type

**Residential rooftops**: Population density, carrier competition, 5G presence,
median home value, multi-family %, HPI trend

**Commercial buildings**: CRE index, co-location potential, carrier competition,
commuter count, broadband availability, professional employment %

**Rooftop (general)**: Tower height (from ASR), structure type (BANT/BTWR),
5G NR presence, nearest tower distance, fiber availability

**Empty plots**: Tower scarcity (density), nearest tower distance, co-location
potential, zoning restrictiveness, parcel size, highway proximity